#!/usr/bin/env node
/**
 * Génère les CountryProfile TypeScript pour les pays manquants
 * (non présents dans COUNTRY_PROFILES, mais dans game-provinces.json)
 * Output: code TS à coller dans countryProfiles.ts
 */
import { readFileSync, writeFileSync } from 'fs';

// Province counts from game-provinces.json (generated by build_game_provinces.mjs)
const provinces = JSON.parse(readFileSync('apps/client/public/game-provinces.json', 'utf8'));
const provinceCounts = {};
for (const f of provinces.features) {
  const id = f.properties.countryId;
  provinceCounts[id] = (provinceCounts[id] || 0) + 1;
}

// IDs already in COUNTRY_PROFILES (44 game countries)
const GAME_IDS = new Set([
  'usa','brazil','germany','russia','india','japan','nigeria','france','china','saudi',
  'australia','sweden','algeria','morocco','tunisia','libya','israel','palestine',
  'uk','spain','italy','poland','ukraine','turkey','norway','netherlands','greece',
  'south_korea','indonesia','vietnam','thailand','pakistan','iran','iraq',
  'south_africa','egypt','kenya','ethiopia','canada','mexico','argentina','chile',
  'colombia','peru',
]);

// Per-country data: [name_fr, flag, oil, iron, coal, rareEarths, precious, uranium, agriTotal, water, money, pop, regions[], strengths[], weaknesses[], researchB, militaryB, tradeB, agricultureB]
// regions array length MUST match province count in game-provinces.json
const DATA = {
  // ─── Afrique Sub-saharienne ───────────────────────────────────────────────
  tanzania:           ['Tanzanie',         '🇹🇿', 5,  10, 3,  8,  10, 2,  65, 50, 3000, 6.1,  ['Nord','Dar es Salaam','Intérieur','Sud'],           ['Safari & tourisme','Agriculture','Or'],               ['Infrastructure','Eau rare en saison','Peu d\'industrie'],  5, 8, 10, 16],
  somalia:            ['Somalie',           '🇸🇴', 10, 5,  2,  3,  5,  0,  25, 15, 2200, 1.7,  ['Mogadiscio','Centre'],                               ['Pêche','Bétail','Côte stratégique'],                  ['Instabilité politique','Sécheresse','Peu de ressources'], 3, 10, 8,  10],
  sudan:              ['Soudan',            '🇸🇩', 40, 15, 8,  5,  8,  2,  45, 30, 2800, 4.5,  ['Khartoum','Nord','Est','Sud'],                       ['Pétrole','Agriculture du Nil','Bétail'],              ['Instabilité','Sécheresse','Peu d\'industrie'],             4, 12, 8,  12],
  s_sudan:            ['Soudan du Sud',     '🇸🇸', 45, 5,  3,  3,  5,  0,  35, 40, 2500, 1.2,  ['Juba','Nord','Sud'],                                 ['Pétrole','Eau du Nil','Bétail'],                      ['Guerre civile','Infrastructure nulle','Enclavement'],     3, 10, 6,  12],
  chad:               ['Tchad',             '🇹🇩', 30, 5,  2,  2,  3,  0,  30, 20, 2300, 1.7,  ['N\'Djamena','Nord','Sud','Est'],                     ['Pétrole','Bétail','Uranium potentiel'],               ['Enclavement','Désert','Instabilité'],                      3, 10, 6,  12],
  dem_rep_congo:      ['RD Congo',          '🇨🇩', 10, 30, 5, 25,  15, 3,  60, 80, 2800, 9.5,  ['Kinshasa','Est','Nord','Sud'],                       ['Cobalt','Mines','Forêt tropicale','Eau'],             ['Instabilité','Infrastructure','Corruption'],               4, 10, 8,  14],
  angola:             ['Angola',            '🇦🇴', 65, 15, 8,  8,  12, 2,  45, 40, 3500, 3.4,  ['Luanda','Nord','Centre','Sud'],                      ['Pétrole offshore','Diamants','Bois tropical'],        ['Corruption','Infrastructure','Eau limitée'],               5, 10, 10, 10],
  mozambique:         ['Mozambique',        '🇲🇿', 15, 10, 20, 5,  8,  0,  55, 50, 2800, 3.2,  ['Maputo','Centre','Nord','Zambèze'],                  ['Gaz naturel','Agriculture','Côte Indienne'],          ['Pauvreté','Cyclones','Infrastructure faible'],             4, 7,  10, 14],
  zambia:             ['Zambie',            '🇿🇲', 3,  20, 10, 5,  15, 2,  50, 60, 2800, 1.9,  ['Lusaka','Copperbelt','Nord'],                        ['Cuivre','Eau douce','Agriculture'],                   ['Enclavement','Dépendance minière','Pauvreté'],             5, 7,  10, 14],
  zimbabwe:           ['Zimbabwe',          '🇿🇼', 0,  15, 8,  8,  12, 2,  50, 35, 2800, 1.6,  ['Harare','Bulawayo','Nord'],                          ['Platine','Chrome','Agriculture passée'],              ['Inflation','Instabilité','Infrastructure'],                5, 8,  8,  12],
  botswana:           ['Botswana',          '🇧🇼', 0,  5,  3,  3,  30, 0,  25, 20, 4200, 0.3,  ['Gaborone','Désert','Nord'],                          ['Diamants','Stabilité','Tourisme safari'],             ['Eau très limitée','Économie mono-produit','Enclavement'], 8, 5,  14, 6],
  namibia:            ['Namibie',           '🇳🇦', 5,  10, 5,  5,  20, 3,  20, 15, 4000, 0.3,  ['Windhoek','Nord','Côte','Sud'],                      ['Diamants','Uranium','Pêche','Tourisme'],              ['Eau critique','Population très faible','Désert'],          7, 6,  12, 6],
  madagascar:         ['Madagascar',        '🇲🇬', 2,  10, 2, 15,  15, 0,  55, 55, 2500, 2.7,  ['Nord','Centre','Sud'],                               ['Vanille','Nickel','Biodiversité'],                    ['Infrastructure','Cyclones','Pauvreté'],                    5, 5,  10, 16],
  malawi:             ['Malawi',            '🇲🇼', 0,  5,  2,  3,  5,  0,  55, 60, 2300, 2.0,  ['Lilongwe','Lac Malawi'],                             ['Agriculture','Lac','Tabac'],                         ['Enclavement','Peu de ressources','Pauvreté'],              4, 5,  8,  16],
  eswatini:           ['Eswatini',          '🇸🇿', 0,  5,  2,  3,  5,  0,  45, 40, 3000, 0.1,  ['Mbabane','Manzini'],                                 ['Agriculture','Sucre','Stabilité'],                   ['Enclavé dans Afrique du Sud','Peu d\'industrie'],          5, 5,  10, 14],
  lesotho:            ['Lesotho',           '🇱🇸', 0,  5,  2,  2,  8,  0,  40, 70, 2500, 0.2,  ['Maseru','Montagnes'],                                ['Eau (Lesotho Highlands)','Diamants','Laine'],         ['Enclavé','Montagneux','Économie faible'],                  4, 5,  8,  14],
  burundi:            ['Burundi',           '🇧🇮', 0,  5,  2,  3,  5,  0,  55, 50, 2200, 1.3,  ['Bujumbura','Est'],                                   ['Agriculture','Café','Lac Tanganyika'],               ['Instabilité','Surpopulation','Peu de ressources'],         3, 8,  6,  16],
  rwanda:             ['Rwanda',            '🇷🇼', 0,  5,  2,  3,  5,  0,  55, 50, 3200, 1.4,  ['Kigali','Ouest'],                                    ['Stabilité','Café','Tourisme gorilles'],              ['Enclavé','Peu de ressources','Trop dense'],                8, 6,  10, 14],
  uganda:             ['Ouganda',           '🇺🇬', 15, 5,  2,  5,  5,  0,  65, 55, 2800, 4.8,  ['Kampala','Nord','Lac Victoria'],                    ['Agriculture','Café','Pétrole émergent'],              ['Infrastructure','Instabilité nord','Santé'],               5, 7,  8,  16],
  cameroon:           ['Cameroun',          '🇨🇲', 25, 10, 5,  5,  8,  0,  60, 60, 3200, 2.8,  ['Yaoundé','Douala','Nord'],                           ['Pétrole','Cacao','Bois'],                            ['Corruption','Infrastructure','Instabilité'],               5, 8,  10, 14],
  ghana:              ['Ghana',             '🇬🇭', 25, 15, 5,  5,  10, 0,  60, 50, 3500, 3.2,  ['Accra','Centre','Nord'],                             ['Or','Cacao','Pétrole','Stabilité'],                  ['Infrastructure','Endettement','Énergie'],                  8, 7,  12, 14],
  c_te_d_ivoire:      ['Côte d\'Ivoire',   '🇨🇮', 10, 8,  2,  5,  8,  0,  70, 55, 3500, 2.7,  ['Abidjan','Centre','Nord'],                           ['Cacao mondial','Caoutchouc','Commerce'],              ['Agriculture fragile','Instabilité','Inégalités'],          5, 8,  14, 16],
  senegal:            ['Sénégal',           '🇸🇳', 10, 5,  2,  3,  5,  0,  55, 40, 3000, 1.7,  ['Dakar','Intérieur'],                                 ['Phosphates','Pêche','Stabilité'],                    ['Peu de pétrole','Sécheresse','Pauvreté'],                  7, 5,  12, 14],
  mali:               ['Mali',              '🇲🇱', 5,  8,  2,  3,  12, 2,  30, 30, 2500, 2.2,  ['Bamako','Nord','Sahara','Sahel'],                    ['Or','Coton','Uranium potentiel'],                    ['Désert','Instabilité','Enclavement'],                      3, 10, 6,  10],
  mauritania:         ['Mauritanie',        '🇲🇷', 15, 30, 5,  3,  8,  0,  15, 10, 2800, 0.5,  ['Nouakchott','Intérieur','Nord','Côte'],               ['Fer','Pêche','Or','Pétrole émergent'],               ['Désert','Eau critique','Population faible'],               4, 8,  8,  6],
  niger:              ['Niger',             '🇳🇪', 5,  5,  2,  5,  8,  25, 25, 20, 2300, 2.5,  ['Niamey','Désert Nord','Est','Sahel'],                ['Uranium','Or','Bétail'],                             ['Sécheresse','Enclavement','Pauvreté'],                     3, 8,  6,  10],
  burkina_faso:       ['Burkina Faso',      '🇧🇫', 0,  5,  2,  2,  10, 0,  50, 35, 2500, 2.2,  ['Ouagadougou','Sahel','Sud'],                         ['Or','Coton','Bétail'],                               ['Enclavement','Sécheresse','Instabilité'],                  4, 7,  8,  14],
  guinea:             ['Guinée',            '🇬🇳', 5,  30, 5,  5,  8,  0,  60, 70, 2800, 1.4,  ['Conakry','Intérieur','Nord'],                        ['Bauxite mondiale','Or','Agriculture'],               ['Infrastructure','Instabilité','Peu d\'industrie'],         4, 8,  8,  14],
  guinea_bissau:      ['Guinée-Bissau',     '🇬🇼', 5,  2,  1,  2,  2,  0,  50, 40, 2200, 0.2,  ['Bissau','Intérieur'],                                ['Noix de cajou','Pêche'],                             ['Instabilité','Peu de ressources','Enclavé'],               3, 5,  8,  14],
  sierra_leone:       ['Sierra Leone',      '🇸🇱', 0,  5,  2,  5,  15, 0,  50, 70, 2500, 0.8,  ['Freetown','Intérieur'],                              ['Diamants','Fer','Agriculture'],                      ['Post-conflit','Infrastructure','Pauvreté'],                4, 5,  8,  12],
  liberia:            ['Libéria',           '🇱🇷', 5,  10, 2,  3,  5,  0,  55, 75, 2500, 0.5,  ['Monrovia','Intérieur'],                              ['Fer','Caoutchouc','Bois'],                           ['Post-conflit','Infrastructure','Corruption'],              4, 5,  8,  14],
  togo:               ['Togo',              '🇹🇬', 0,  5,  2,  3,  8,  0,  55, 50, 2500, 0.8,  ['Lomé','Nord'],                                       ['Phosphates','Agriculture','Port'],                  ['Peu de ressources','Enclavement','Pauvreté'],              5, 5,  10, 14],
  benin:              ['Bénin',             '🇧🇯', 5,  3,  2,  2,  3,  0,  55, 45, 2500, 1.2,  ['Cotonou','Nord'],                                    ['Agriculture','Commerce informel','Coton'],           ['Peu d\'industrie','Instabilité','Infrastructure'],         4, 5,  10, 14],
  gabon:              ['Gabon',             '🇬🇦', 45, 5,  2,  3,  5,  0,  40, 70, 5000, 0.2,  ['Libreville','Centre','Sud'],                         ['Pétrole','Manganèse','Bois tropical'],               ['Population faible','Post-pétrole','Inégalités'],          7, 7,  12, 8],
  congo:              ['République du Congo','🇨🇬', 40, 5,  2,  3,  5,  0,  45, 70, 3800, 0.6,  ['Brazzaville','Pointe-Noire','Nord'],                 ['Pétrole','Bois','Agriculture'],                      ['Corruption','Infrastructure','Dépendance pétrole'],       5, 8,  10, 10],
  central_african_rep:['Centrafrique',      '🇨🇫', 0,  5,  2,  5,  15, 2,  45, 55, 2200, 0.5,  ['Bangui','Nord','Sud'],                               ['Diamants','Or','Bois'],                              ['Instabilité grave','Enclavement','Pauvreté'],              3, 8,  6,  12],
  eq_guinea:          ['Guinée équatoriale','🇬🇶', 50, 5,  2,  2,  5,  0,  35, 55, 6000, 0.2,  ['Malabo','Bata'],                                     ['Pétrole offshore','Capital élevé'],                  ['Population minuscule','Corruption','Post-pétrole'],        4, 6,  10, 6],
  eritrea:            ['Érythrée',          '🇪🇷', 0,  15, 2,  3,  5,  0,  25, 20, 2500, 0.4,  ['Asmara','Côte'],                                     ['Mines','Pêche','Côte stratégique'],                  ['Isolement','Régime autoritaire','Infrastructure'],          3, 12, 6,  8],
  djibouti:           ['Djibouti',          '🇩🇯', 0,  0,  0,  0,  0,  0,  5,  10, 3500, 0.1,  ['Djibouti Ville','Intérieur'],                        ['Position stratégique','Port','Services'],            ['Quasi pas de ressources','Eau nulle','Petit'],            5, 8,  18, 2],
  somaliland:         ['Somaliland',        '🇸🇴', 5,  3,  1,  2,  3,  0,  20, 15, 2500, 0.4,  ['Hargeisa','Côte'],                                   ['Stabilité relative','Bétail','Côte'],                ['Non reconnu','Peu de ressources','Isolé'],                 3, 8,  8,  8],
  gambia:             ['Gambie',            '🇬🇲', 0,  2,  1,  1,  2,  0,  45, 40, 2500, 0.2,  ['Banjul','Intérieur'],                                ['Tourisme','Arachides','Pêche'],                      ['Enclavement','Très petit','Peu de ressources'],            4, 4,  10, 14],

  // ─── Maghreb / Proche-Orient ──────────────────────────────────────────────
  w_sahara:           ['Sahara occidental', '🇪🇭', 0,  5,  2, 10,  80, 0,  5,  5,  1500, 0.1,  ['Nord','Sud'],                                        ['Phosphates','Pêche','Stabilité fragile'],            ['Statut contesté','Désert','Population infime'],            2, 5,  6,  4],
  jordan:             ['Jordanie',          '🇯🇴', 5,  5,  3,  3,  8,  2,  30, 20, 3500, 1.0,  ['Amman','Aqaba'],                                     ['Position stratégique','Phosphates','Stabilité'],     ['Quasi pas de pétrole','Eau critique','Dépendance aid'],   8, 8,  12, 8],
  lebanon:            ['Liban',             '🇱🇧', 5,  5,  2,  5,  5,  0,  45, 30, 3000, 0.7,  ['Beyrouth','Intérieur'],                              ['Services bancaires','Diaspora','Agriculture'],       ['Crise économique','Instabilité','Peu de ressources'],      9, 5,  14, 10],
  syria:              ['Syrie',             '🇸🇾', 30, 5,  5,  3,  5,  0,  40, 25, 2500, 2.1,  ['Damas','Nord'],                                      ['Pétrole','Agriculture','Histoire'],                  ['Guerre','Infrastructure détruite','Sanctions'],            4, 10, 6,  10],
  united_arab_emirates:['Émirats arabes unis','🇦🇪', 90, 5,  2,  3,  10, 0,  5,  5,  8000, 1.0,  ['Abu Dhabi','Dubaï'],                                 ['Pétrole','Finance','Hub mondial','Logistique'],      ['Eau critique','Dépendance pétrole','Population importée'],7, 8,  22, 2],
  qatar:              ['Qatar',             '🇶🇦', 80, 3,  2,  2,  5,  0,  5,  5,  9000, 0.3,  ['Doha','Intérieur'],                                  ['Gaz naturel','Finance','Hub'],                       ['Eau critique','Population infime','Dépendance'],          6, 7,  20, 2],
  kuwait:             ['Koweït',            '🇰🇼', 90, 3,  2,  2,  5,  0,  5,  5,  9000, 0.4,  ['Koweït City','Al Ahmadi'],                           ['Pétrole immense','Fonds souverain','Finance'],       ['Eau nulle','Agriculture nulle','Petit'],                   5, 7,  20, 2],
  oman:               ['Oman',              '🇴🇲', 55, 5,  2,  3,  5,  2,  10, 15, 5000, 0.5,  ['Mascate','Dhofar','Intérieur'],                      ['Pétrole','Gaz','Position maritime'],                 ['Eau limitée','Post-pétrole','Agriculture nulle'],          5, 8,  14, 4],
  yemen:              ['Yémen',             '🇾🇪', 25, 5,  2,  3,  5,  0,  35, 15, 2000, 3.3,  ['Sanaa','Aden','Est'],                                ['Pétrole','Pêche','Agriculture'],                     ['Guerre','Infrastructure détruite','Eau critique'],         3, 10, 6,  8],
  n_cyprus:           ['Chypre du Nord',    '🇨🇾', 0,  3,  1,  2,  3,  0,  40, 30, 3500, 0.4,  ['Nicosie Nord','Famagouste'],                         ['Agriculture','Tourisme','Position'],                 ['Non reconnu','Peu de ressources','Économie limitée'],      6, 5,  12, 12],
  cyprus:             ['Chypre',            '🇨🇾', 0,  3,  2,  2,  5,  0,  45, 30, 4500, 0.9,  ['Nicosie','Limassol'],                                ['Tourisme','Services','Gaz offshore'],               ['Division','Eau limitée','Dépendance imports'],            8, 5,  16, 10],

  // ─── Europe ──────────────────────────────────────────────────────────────
  austria:            ['Autriche',          '🇦🇹', 5,  10, 5,  3,  5,  2,  55, 65, 5200, 0.9,  ['Vienne','Provinces'],                                ['Industrie','Tourisme','Finance'],                    ['Peu d\'énergie fossile','Petit','Dépendance imports'],    12, 6,  14, 10],
  belgium:            ['Belgique',          '🇧🇪', 5,  5,  5,  3,  3,  2,  50, 50, 5300, 1.2,  ['Bruxelles','Flandre'],                               ['Finance','Chimie','Hub européen'],                   ['Peu de ressources','Dépendance','Politique fragile'],     12, 5,  16, 8],
  switzerland:        ['Suisse',            '🇨🇭', 0,  5,  2,  2,  5,  0,  40, 60, 6500, 0.9,  ['Zurich','Genève'],                                   ['Finance','Pharma','Industrie de précision'],         ['Pas de pétrole','Importation massive','Petit'],           16, 4,  18, 6],
  portugal:           ['Portugal',          '🇵🇹', 5,  5,  3,  3,  5,  0,  60, 45, 4200, 1.0,  ['Lisbonne','Porto'],                                  ['Agriculture','Pêche','Tourisme','Cork'],             ['Peu de pétrole','Dépendance','Industrie légère'],          8, 5,  14, 14],
  ireland:            ['Irlande',           '🇮🇪', 10, 5,  2,  2,  3,  0,  50, 70, 5800, 0.5,  ['Dublin','Ouest'],                                    ['Tech hub','Pharma','Agriculture verte'],             ['Pas d\'énergie fossile','Petit','Dépendance UK/EU'],      15, 4,  16, 10],
  denmark:            ['Danemark',          '🇩🇰', 20, 5,  5,  2,  5,  2,  45, 60, 5800, 0.6,  ['Copenhague','Jutland'],                              ['Agriculture','Éolien','Pêche','Commerce'],           ['Petit','Peu de minerais','Coûts élevés'],                 14, 6,  14, 12],
  finland:            ['Finlande',          '🇫🇮', 5,  15, 5,  3,  5,  2,  35, 80, 5500, 0.6,  ['Helsinki','Laponie','Lakeland'],                     ['Bois','High-tech Nokia','Eau','Mines'],              ['Population faible','Hiver long','Peu de pétrole'],        15, 6,  12, 8],
  iceland:            ['Islande',           '🇮🇸', 0,  5,  0,  2,  3,  0,  20, 90, 5800, 0.04, ['Reykjavik','Intérieur'],                             ['Géothermie','Pêche','Eau','Aluminium'],              ['Population infime','Petit','Dépendance imports'],         13, 4,  14, 6],
  luxembourg:         ['Luxembourg',        '🇱🇺', 0,  5,  2,  2,  2,  0,  40, 50, 7000, 0.07, ['Luxembourg Ville','Campagne'],                       ['Finance','Fonds','Acier historique'],                ['Très petit','Peu de ressources','Dépendant EU'],          10, 3,  22, 6],
  belgium:            ['Belgique',          '🇧🇪', 5,  5,  5,  3,  3,  2,  50, 50, 5300, 1.2,  ['Bruxelles','Flandre'],                               ['Finance','Chimie','Hub européen'],                   ['Peu de ressources','Dépendance','Politique fragile'],     12, 5,  16, 8],
  czechia:            ['Tchéquie',          '🇨🇿', 3,  10, 15, 3,  5,  2,  55, 55, 4800, 1.1,  ['Prague','Moravie'],                                  ['Industrie','Automobile','Bière'],                    ['Peu d\'énergie propre','Charbon','Petit'],                11, 8,  12, 10],
  slovakia:           ['Slovaquie',         '🇸🇰', 2,  8,  8,  3,  3,  2,  55, 55, 4200, 0.5,  ['Bratislava','Est'],                                  ['Automobile','Industrie','Agriculture'],              ['Petit','Peu de ressources','Dépendance imports'],          9, 7,  12, 12],
  hungary:            ['Hongrie',           '🇭🇺', 5,  5,  5,  3,  3,  2,  65, 50, 4000, 1.0,  ['Budapest','Campagne'],                               ['Agriculture','Industrie','Énergie nucléaire'],       ['Peu d\'énergie','Géopolitique','Inflation'],               9, 7,  10, 14],
  romania:            ['Roumanie',          '🇷🇴', 20, 15, 12, 5,  5,  2,  65, 50, 3600, 1.9,  ['Bucarest','Transylvanie','Moldavie'],                ['Pétrole','Agriculture','Industrie'],                 ['Corruption','Émigration','Infrastructure'],                8, 8,  10, 14],
  bulgaria:           ['Bulgarie',          '🇧🇬', 5,  8,  10, 3,  5,  2,  60, 50, 3500, 0.7,  ['Sofia','Côte'],                                      ['Agriculture','Tourisme','Mines'],                    ['Émigration','Corruption','Infrastructure'],                7, 6,  10, 14],
  moldova:            ['Moldavie',          '🇲🇩', 2,  3,  3,  2,  2,  0,  65, 45, 2800, 0.3,  ['Chișinău','Transnistrie'],                           ['Agriculture','Vin','Services'],                      ['Pauvreté','Dépendance','Politique instable'],              6, 5,  10, 16],
  belarus:            ['Biélorussie',       '🇧🇾', 5,  5,  5,  3,  3,  0,  60, 55, 3500, 0.9,  ['Minsk','Ouest','Est'],                               ['Potasse','Industrie soviétique','Agriculture'],      ['Régime autoritaire','Sanctions','Dépendance Russie'],      6, 10, 6,  12],
  lithuania:          ['Lituanie',          '🇱🇹', 2,  5,  3,  2,  2,  0,  50, 50, 4500, 0.3,  ['Vilnius','Kaunas'],                                  ['Agriculture','Ambre','Commerce Baltique'],           ['Petit','Peu de ressources','Dépendance énergétique'],      9, 6,  12, 12],
  latvia:             ['Lettonie',          '🇱🇻', 2,  5,  2,  2,  2,  0,  45, 55, 4300, 0.2,  ['Riga','Latgale'],                                    ['Bois','Commerce maritime','Agri'],                   ['Émigration','Peu de ressources','Petit'],                  8, 6,  12, 12],
  estonia:            ['Estonie',           '🇪🇪', 5,  5,  5,  2,  2,  0,  45, 55, 5000, 0.15, ['Tallinn','Tartu'],                                   ['Numérique','Schiste bitumineux','Bois'],             ['Très petit','Peu de ressources','Démographie'],            14, 5,  12, 10],
  albania:            ['Albanie',           '🇦🇱', 5,  10, 5,  5,  5,  0,  55, 50, 3200, 0.3,  ['Tirana','Sud'],                                      ['Chrome','Agriculture','Tourisme émergent'],          ['Infrastructure','Corruption','Émigration'],                5, 7,  10, 14],
  croatia:            ['Croatie',           '🇭🇷', 10, 5,  3,  2,  3,  0,  55, 50, 4200, 0.4,  ['Zagreb','Côte dalmate'],                             ['Tourisme','Agriculture','Commerce'],                 ['Petit','Peu de ressources','Post-conflit'],                8, 6,  14, 12],
  slovenia:           ['Slovénie',          '🇸🇮', 2,  5,  3,  3,  3,  0,  45, 65, 5000, 0.2,  ['Ljubljana','Alpes'],                                 ['Industrie','Tourisme','Eau'],                        ['Très petit','Peu de pétrole','Dépendance'],                10, 5,  12, 10],
  bosnia_and_herz:    ['Bosnie-Herzégovine','🇧🇦', 3,  10, 12, 3,  3,  0,  55, 55, 3000, 0.3,  ['Sarajevo','Republika Srpska'],                       ['Agriculture','Bois','Industrie lourde'],             ['Instabilité','Post-conflit','Infrastructure'],             5, 8,  8,  14],
  serbia:             ['Serbie',            '🇷🇸', 5,  10, 12, 5,  5,  0,  60, 55, 3800, 0.7,  ['Belgrade','Vojvodine'],                              ['Agriculture','Industrie','Mines'],                   ['Dépendance énergétique','Instabilité','Infrastructure'],   7, 8,  10, 14],
  montenegro:         ['Monténégro',        '🇲🇪', 0,  5,  3,  3,  3,  0,  45, 60, 4000, 0.06, ['Podgorica','Côte'],                                  ['Tourisme','Aluminium','Agriculture'],                ['Très petit','Peu de ressources','Dépendance'],             6, 5,  12, 12],
  albania:            ['Albanie',           '🇦🇱', 5,  10, 5,  5,  5,  0,  55, 50, 3200, 0.3,  ['Tirana','Sud'],                                      ['Chrome','Agriculture','Tourisme émergent'],          ['Infrastructure','Corruption','Émigration'],                5, 7,  10, 14],
  macedonia:          ['Macédoine du Nord', '🇲🇰', 2,  8,  5,  3,  3,  0,  55, 45, 3200, 0.2,  ['Skopje','Lac Ohrid'],                                ['Chrome','Agriculture','Tourisme'],                   ['Enclavement','Peu de ressources','Emploi faible'],         6, 6,  10, 14],
  kosovo:             ['Kosovo',            '🇽🇰', 5,  8,  40, 3,  5,  0,  50, 45, 2800, 0.2,  ['Pristina','Metohija'],                                ['Lignite','Agriculture','Jeunesse'],                 ['Statut disputé','Économie fragile','Dépendance'],          5, 8,  8,  12],
  portugal:           ['Portugal',          '🇵🇹', 5,  5,  3,  3,  5,  0,  60, 45, 4200, 1.0,  ['Lisbonne','Porto'],                                  ['Agriculture','Pêche','Tourisme'],                    ['Peu de pétrole','Dépendance','Industrie légère'],          8, 5,  14, 14],

  // ─── Caucase / Asie Centrale ──────────────────────────────────────────────
  georgia:            ['Géorgie',           '🇬🇪', 5,  5,  5,  3,  5,  0,  55, 55, 3500, 0.4,  ['Tbilissi','Ouest'],                                  ['Vin','Tourisme','Mines','Agriculture'],              ['Instabilité régionale','Peu d\'énergie','Corruption'],    8, 7,  12, 14],
  armenia:            ['Arménie',           '🇦🇲', 0,  10, 5,  5,  5,  0,  45, 35, 3200, 0.3,  ['Erevan','Province'],                                 ['Mines','Brandy','Diaspora tech'],                    ['Enclavé','Peu de pétrole','Instabilité'],                  9, 8,  10, 12],
  azerbaijan:         ['Azerbaïdjan',       '🇦🇿', 60, 10, 5,  5,  5,  0,  40, 30, 4500, 1.0,  ['Bakou','Karabakh'],                                  ['Pétrole','Gaz','Position stratégique'],              ['Corruption','Post-pétrole','Instabilité'],                 7, 10, 12, 8],
  kazakhstan:         ['Kazakhstan',        '🇰🇿', 70, 35, 25, 20, 20, 12, 40, 25, 4800, 1.9,  ['Astana','Almaty','Ouest','Est'],                     ['Pétrole','Uranium','Mines','Agriculture'],           ['Enclavé','Eau limitée','Dépendance énergie'],              7, 10, 10, 10],
  uzbekistan:         ['Ouzbékistan',       '🇺🇿', 15, 5,  5,  5,  5,  2,  55, 20, 3000, 3.5,  ['Tachkent','Samarcande','Fergana'],                   ['Coton','Or','Agriculture','Position silk road'],     ['Eau Aral','Enclavé','Dépendance'],                         6, 8,  10, 14],
  turkmenistan:       ['Turkménistan',      '🇹🇲', 30, 5,  5,  3,  3,  2,  25, 15, 3800, 0.6,  ['Achgabat','Mer Caspienne','Désert'],                 ['Gaz naturel','Coton','Position stratégique'],        ['Régime autoritaire','Eau critique','Dépendance gaz'],      4, 8,  8,  8],
  tajikistan:         ['Tadjikistan',       '🇹🇯', 2,  5,  5,  5,  5,  0,  45, 70, 2500, 1.0,  ['Douchanbe','Montagnes'],                             ['Aluminium','Eau','Agriculture'],                     ['Enclavé','Pauvreté','Instabilité'],                         4, 8,  8,  12],
  kyrgyzstan:         ['Kirghizistan',      '🇰🇬', 2,  5,  5,  5,  5,  0,  45, 65, 2800, 0.7,  ['Bichkek','Osh'],                                     ['Or','Eau','Tourisme montagne'],                      ['Enclavé','Pauvreté','Instabilité'],                         5, 7,  8,  12],
  afghanistan:        ['Afghanistan',       '🇦🇫', 5,  10, 5, 25,  10, 0,  45, 30, 2000, 4.0,  ['Kaboul','Nord','Sud'],                               ['Terres rares','Lithium','Agriculture'],              ['Instabilité grave','Enclavé','Infrastructure nulle'],       2, 10, 4,  10],

  // ─── Asie du Sud ─────────────────────────────────────────────────────────
  bangladesh:         ['Bangladesh',        '🇧🇩', 10, 5,  5,  2,  2,  0,  70, 50, 3200, 17.0, ['Dacca','Delta'],                                     ['Textile','Riz','Pêche','Main-d\'œuvre'],             ['Inondations','Surpopulation','Peu de ressources'],          5, 7,  12, 16],
  nepal:              ['Népal',             '🇳🇵', 0,  5,  2,  3,  5,  0,  55, 80, 2500, 3.0,  ['Katmandou','Himalaya'],                              ['Hydroélectricité','Tourisme','Agriculture'],          ['Enclavé','Pauvreté','Infrastructure'],                      5, 5,  8,  14],
  bhutan:             ['Bhoutan',           '🇧🇹', 0,  3,  1,  2,  3,  0,  45, 80, 4000, 0.08, ['Thimphou','Montagnes'],                              ['Hydroélectricité','Bonheur','Tourisme limité'],      ['Très petit','Enclavé','Peu de ressources'],                 8, 4,  8,  14],
  sri_lanka:          ['Sri Lanka',         '🇱🇰', 0,  5,  2,  5,  5,  0,  65, 60, 3500, 2.2,  ['Colombo','Kandy'],                                   ['Thé','Tourisme','Épices','Pêche'],                   ['Peu de pétrole','Dette','Infrastructure'],                  7, 5,  12, 16],

  // ─── Asie du Sud-Est ─────────────────────────────────────────────────────
  myanmar:            ['Myanmar',           '🇲🇲', 10, 20, 8, 10,  15, 2,  70, 65, 2800, 5.4,  ['Yangon','Mandalay','Nord'],                          ['Jade','Rubis','Agriculture','Bois'],                 ['Instabilité','Sanctions','Peu d\'industrie'],              4, 10, 8,  16],
  cambodia:           ['Cambodge',          '🇰🇭', 5,  5,  2,  3,  3,  0,  65, 60, 2800, 1.7,  ['Phnom Penh','Provinces'],                            ['Riz','Tourisme Angkor','Textile'],                   ['Peu d\'industrie','Infrastructure','Corruption'],           5, 5,  10, 16],
  laos:               ['Laos',              '🇱🇦', 5,  10, 5,  5,  5,  0,  65, 70, 2800, 0.7,  ['Vientiane','Nord','Sud'],                            ['Hydroélectricité','Mines','Agriculture'],            ['Enclavé','Pauvreté','Infrastructure'],                      5, 6,  8,  14],
  timor_leste:        ['Timor-Leste',       '🇹🇱', 20, 3,  2,  2,  3,  0,  50, 50, 3000, 0.1,  ['Dili','Intérieur'],                                  ['Pétrole offshore','Agriculture','Café'],             ['Très petit','Post-conflit','Infrastructure'],               4, 5,  8,  14],
  philippines:        ['Philippines',       '🇵🇭', 10, 15, 5, 10,  10, 0,  70, 65, 3500, 11.0, ['Manille','Visayas','Mindanao'],                      ['BPO','Agriculture','Ressources marines'],            ['Typhons','Infrastructure insulaire','Corruption'],          7, 7,  12, 14],
  malaysia:           ['Malaisie',          '🇲🇾', 50, 10, 5, 10,  10, 0,  65, 65, 4500, 3.3,  ['Kuala Lumpur','Sabah','Sarawak'],                    ['Pétrole','Palme','Électronique'],                    ['Dépendance pétrole','Inégalités','Eau Sarawak'],            9, 7,  13, 12],
  brunei:             ['Brunéi',            '🇧🇳', 60, 3,  2,  2,  3,  0,  20, 30, 7000, 0.05, ['Bandar Seri Begawan','Intérieur'],                   ['Pétrole','Gaz','Fonds souverain'],                   ['Très petit','Post-pétrole','Dépendance'],                   5, 6,  14, 4],
  mongolia:           ['Mongolie',          '🇲🇳', 5,  25, 20, 15, 10, 5,  25, 20, 3200, 0.3,  ['Oulan-Bator','Steppe Est','Désert Gobi','Nord'],     ['Charbon','Cuivre','Élevage','Terres rares'],         ['Enclavé','Hiver extreme','Peu de population'],             5, 8,  8,  10],
  north_korea:        ['Corée du Nord',     '🇰🇵', 5,  20, 25, 10, 5,  5,  35, 40, 2000, 2.6,  ['Pyongyang','Nord'],                                  ['Mines','Armée','Agriculture'],                       ['Régime isolé','Sanctions','Économie fermée'],               6, 18, 0,  8],
  taiwan:             ['Taïwan',            '🇹🇼', 5,  5,  5,  5,  5,  2,  40, 40, 5500, 2.4,  ['Taipei','Sud'],                                      ['Semi-conducteurs','Électronique','Commerce'],        ['Revendication Chine','Peu de ressources','Petit'],         20, 8,  16, 4],
  new_zealand:        ['Nouvelle-Zélande',  '🇳🇿', 5,  10, 5,  5,  10, 0,  65, 70, 5500, 0.5,  ['Auckland','Wellington','Sud'],                       ['Agriculture','Laine','Pêche','Tourisme'],            ['Population faible','Isolé','Peu de minerais'],            12, 4,  14, 16],
  papua_new_guinea:   ['Papouasie-Nvl-Guinée','🇵🇬', 15, 15, 5, 10, 20, 2,  60, 80, 3000, 1.0,  ['Port Moresby','Highlands','Côte'],                   ['Or','Cuivre','PNG LNG','Biodiversité'],              ['Infrastructure nulle','Instabilité','Enclavé'],            4, 8,  8,  12],
  solomon_is:         ['Îles Salomon',      '🇸🇧', 0,  5,  2,  2,  3,  0,  55, 70, 2500, 0.07, ['Honiara','Guadalcanal'],                             ['Bois','Pêche','Ressources marines'],                 ['Isolé','Infrastructure','Peu de ressources'],              4, 4,  8,  14],
  vanuatu:            ['Vanuatu',           '🇻🇺', 0,  2,  1,  2,  2,  0,  50, 70, 3000, 0.03, ['Port Vila','Santo'],                                 ['Agriculture','Tourisme','Pêche'],                    ['Vulcans','Isolé','Petit'],                                  4, 4,  10, 14],
  new_caledonia:      ['Nouvelle-Calédonie','🇳🇨', 0,  5,  2, 15, 10, 0,  35, 55, 5500, 0.03, ['Nouméa','Nord'],                                     ['Nickel mondial','Tourisme','Stabilité française'],   ['Dépendance France','Petit','Population faible'],            8, 5,  10, 8],

  // ─── Amériques ───────────────────────────────────────────────────────────
  venezuela:          ['Venezuela',         '🇻🇪', 95, 15, 5,  8,  15, 2,  50, 70, 3200, 2.9,  ['Caracas','Maracaibo','Orénoque','Amazonas'],          ['Pétrole immense','Eau','Biodiversité'],              ['Crise économique','Inflation','Instabilité'],              5, 10, 8,  12],
  bolivia:            ['Bolivie',           '🇧🇴', 20, 10, 5, 25,  15, 5,  55, 60, 3000, 1.2,  ['La Paz','Santa Cruz','Potosí','Oriente'],             ['Lithium','Gaz','Agriculture','Mines'],               ['Enclavé','Infrastructure','Pauvreté'],                      5, 8,  8,  12],
  ecuador:            ['Équateur',          '🇪🇨', 40, 5,  2,  8,  10, 2,  70, 70, 3500, 1.8,  ['Quito','Côte Pacifique','Amazonie'],                 ['Pétrole','Bananes','Cacao','Pêche'],                 ['Dépendance pétrole','Infrastructure','Inégalités'],        6, 7,  10, 14],
  guyana:             ['Guyana',            '🇬🇾', 40, 5,  2,  3,  10, 2,  55, 80, 4000, 0.08, ['Georgetown','Intérieur','Côte'],                     ['Pétrole offshore','Or','Sucre','Bois'],              ['Post-pauvreté','Infrastructure','Petit'],                   6, 5,  10, 12],
  suriname:           ['Suriname',          '🇸🇷', 15, 5,  2,  5,  10, 0,  55, 80, 3800, 0.06, ['Paramaribo','Intérieur'],                            ['Or','Bauxite','Bois','Sucre'],                       ['Infrastructure','Petit','Dépendance'],                      5, 5,  10, 12],
  uruguay:            ['Uruguay',           '🇺🇾', 3,  5,  2,  3,  3,  0,  75, 65, 4500, 0.3,  ['Montevideo','Intérieur'],                            ['Agriculture','Bœuf','Stabilité','Énergies verte'],  ['Petit','Peu de minerais','Dépendance'],                    10, 5,  14, 18],
  paraguay:           ['Paraguay',          '🇵🇾', 0,  5,  2,  3,  3,  0,  65, 70, 3200, 0.7,  ['Asunción','Est','Chaco'],                            ['Soja','Bœuf','Hydroélectricité','Coton'],            ['Enclavé','Peu de ressources','Corruption'],                 5, 5,  10, 16],
  panama:             ['Panama',            '🇵🇦', 0,  5,  2,  3,  5,  0,  45, 65, 5000, 0.4,  ['Panama City','Intérieur'],                           ['Canal','Finance','Commerce mondial'],                ['Peu de ressources','Inégalités','Dépendance'],             8, 5,  20, 8],
  costa_rica:         ['Costa Rica',        '🇨🇷', 0,  5,  2,  3,  3,  0,  60, 75, 4500, 0.5,  ['San José','Provinces'],                             ['Tourisme','Agriculture','Énergies vertes'],          ['Peu de minerais','Infrastructure','Coûts élevés'],         10, 4,  14, 16],
  nicaragua:          ['Nicaragua',         '🇳🇮', 0,  5,  2,  3,  3,  0,  60, 65, 2800, 0.7,  ['Managua','Est'],                                     ['Agriculture','Pêche','Canaux potentiels'],          ['Pauvreté','Infrastructure','Instabilité'],                  4, 7,  8,  14],
  honduras:           ['Honduras',          '🇭🇳', 0,  8,  2,  3,  5,  0,  55, 60, 2800, 1.0,  ['Tegucigalpa','Côte Nord'],                           ['Agriculture','Mines','Pêche'],                      ['Violence','Corruption','Infrastructure'],                   4, 7,  8,  12],
  el_salvador:        ['El Salvador',       '🇸🇻', 0,  3,  2,  2,  3,  0,  55, 50, 3000, 0.6,  ['San Salvador','Intérieur'],                         ['Agriculture','Café','Géothermie'],                  ['Très petit','Violence','Peu de ressources'],               5, 8,  10, 14],
  guatemala:          ['Guatemala',         '🇬🇹', 5,  5,  2,  3,  5,  0,  65, 60, 3200, 1.7,  ['Guatemala City','Intérieur'],                       ['Café','Cardamome','Pétrole','Mines'],                ['Inégalités','Infrastructure','Violence'],                   5, 7,  10, 14],
  belize:             ['Belize',            '🇧🇿', 5,  2,  1,  2,  2,  0,  50, 65, 3500, 0.04, ['Belmopan','Côte'],                                  ['Tourisme','Agriculture','Pêche'],                    ['Très petit','Infrastructure','Peu de ressources'],          6, 5,  10, 12],
  cuba:               ['Cuba',              '🇨🇺', 15, 5,  2,  5,  5,  0,  60, 50, 2800, 1.1,  ['La Havane','Orient'],                               ['Nickel','Tourisme','Médecine','Agriculture'],        ['Sanctions','Économie fermée','Peu d\'industrie'],          8, 8,  6,  14],
  haiti:              ['Haïti',             '🇭🇹', 0,  5,  2,  2,  3,  0,  45, 35, 2200, 1.1,  ['Port-au-Prince','Nord'],                            ['Agriculture','Textile émergent'],                    ['Catastrophes','Pauvreté','Infrastructure nulle'],           3, 6,  6,  14],
  dominican_rep:      ['Rép. Dominicaine',  '🇩🇴', 0,  5,  2,  3,  8,  0,  60, 55, 4000, 1.1,  ['Saint-Domingue','Santiago'],                         ['Tourisme','Or','Agriculture','Zones franches'],     ['Inégalités','Énergie','Dépendance imports'],               7, 5,  14, 12],
  jamaica:            ['Jamaïque',          '🇯🇲', 0,  5,  2,  2,  5,  0,  55, 55, 3500, 0.3,  ['Kingston','Parishes'],                              ['Tourisme','Bauxite','Agriculture'],                  ['Petite','Peu de ressources','Dette'],                       6, 5,  12, 12],
  trinidad_and_tobago:['Trinité-et-Tobago', '🇹🇹', 50, 5,  5,  3,  3,  0,  40, 55, 5500, 0.14, ['Port of Spain','Tobago'],                           ['Pétrole','Gaz','Industrie pétro-chimique'],          ['Post-pétrole','Petit','Dépendance'],                        7, 6,  14, 8],
  puerto_rico:        ['Porto Rico',        '🇵🇷', 0,  3,  1,  2,  2,  0,  45, 50, 4500, 0.3,  ['San Juan','Ouest'],                                  ['Pharma','Tourisme','Agriculture'],                  ['Statut (territoire USA)','Dette','Dépendance'],             9, 4,  12, 10],
  bahamas:            ['Bahamas',           '🇧🇸', 0,  2,  1,  1,  2,  0,  30, 50, 6000, 0.04, ['Nassau','Grand Bahama'],                             ['Tourisme','Finance offshore'],                       ['Petit','Ouragan','Peu de ressources'],                      5, 4,  18, 6],
  falkland_is:        ['Îles Malouines',    '🇫🇰', 0,  2,  1,  2,  2,  0,  20, 60, 5000, 0.003,['Stanley','Intérieur'],                               ['Pêche','Élevage ovin','Pétrole potentiel'],          ['Très petit','Isolé','Revendication Argentine'],             5, 5,  10, 8],
  greenland:          ['Groenland',         '🇬🇱', 0,  10, 5, 10, 10, 5,  10, 80, 5500, 0.06, ['Nuuk','Nord','Est','Ouest'],                         ['Minerais arctiques','Pêche','Potentiel énergétique'],['Population infime','Glace','Dépendance Danemark'],          6, 4,  8,  4],
  fr_s_antarctic_lands:['T.A.A.F.',        '🇹🇫', 0,  2,  1,  3,  3,  0,  5,  50, 1000, 0.001,['Kerguelen','Crozet'],                               ['Pêche','Recherche scientifique'],                    ['Inhabité','Isolé','Pas d\'économie'],                       5, 2,  4,  2],
};

// IDs that need profiles (in provinces but not in GAME_IDS)
const missing = Object.keys(provinceCounts).filter(id => !GAME_IDS.has(id));

// food() helper equivalent
function food(agri) {
  return {
    cereals:    Math.round(agri * 0.40),
    vegetables: Math.round(agri * 0.25),
    sugarOils:  Math.round(agri * 0.20),
    fodder:     Math.round(agri * 0.15),
    redMeat: 0, whiteMeat: 0, dairy: 0, fish: 0,
    steel: 0, fuel: 0, electronicComponents: 0, pharmaceuticals: 0,
    processedFood: 0, fertilizer: 0, phones: 0, computers: 0,
    munitions: 0, obus: 0, bombs: 0,
  };
}

// Generate region names based on province count
function defaultRegions(id, n) {
  const dirs = ['Nord','Centre','Sud','Est','Ouest','Nord-Est','Nord-Ouest','Sud-Est','Sud-Ouest','Intérieur','Côte','Plateau'];
  const regions = [];
  for (let i = 0; i < n; i++) regions.push(dirs[i] || `Région ${i+1}`);
  return regions;
}

let output = '\n  // ─── Pays additionnels (générés) ────────────────────────────────────────\n';

let count = 0;
for (const id of missing) {
  const n = provinceCounts[id];
  const d = DATA[id];
  if (!d) {
    console.warn(`MISSING DATA for ${id} (${n} provinces) — using defaults`);
    continue;
  }
  const [name, flag, oil, iron, coal, re, prec, uran, agri, water, money, pop, regionNamesRaw, strengths, weaknesses, r, m, t, a] = d;

  // regions: use provided names but ensure length matches province count
  let regionNames = Array.isArray(regionNamesRaw) ? [...regionNamesRaw] : [];
  while (regionNames.length < n) regionNames.push(defaultRegions(id, n)[regionNames.length]);
  regionNames = regionNames.slice(0, n);

  const regionsStr = regionNames.map(name => `{ name: '${name.replace(/'/g, "\\'")}' }`).join(', ');
  const strengthsStr = strengths.map(s => `'${s.replace(/'/g, "\\'")}'`).join(', ');
  const weaknessesStr = weaknesses.map(w => `'${w.replace(/'/g, "\\'")}'`).join(', ');

  output += `  {
    id: '${id}',
    name: '${name.replace(/'/g, "\\'")}',
    flag: '${flag}',
    description: '${name.replace(/'/g, "\\'")} — nation jouable dans Empire du Commerce.',
    startingResources: { oil: ${oil}, iron: ${iron}, coal: ${coal}, rareEarths: ${re}, precious: ${prec}, uranium: ${uran}, ...food(${agri}), water: ${water} },
    startingMoney: ${money},
    startingPopulation: ${pop},
    regions: [${regionsStr}],
    strengths: [${strengthsStr}],
    weaknesses: [${weaknessesStr}],
    bonuses: { researchBonus: ${r}, militaryBonus: ${m}, tradeBonus: ${t}, agricultureBonus: ${a} },
  },\n`;
  count++;
}

console.error(`Generated ${count}/${missing.length} profiles`);

// Write to a TS snippet file
writeFileSync('generated_profiles.ts', output, 'utf8');
console.error('Written to generated_profiles.ts');
console.log(output);
