
  // ─── Pays additionnels (générés) ────────────────────────────────────────
  {
    id: 'tanzania',
    name: 'Tanzanie',
    flag: '🇹🇿',
    description: 'Tanzanie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 10, coal: 3, rareEarths: 8, precious: 10, uranium: 2, ...food(65), water: 50 },
    startingMoney: 3000,
    startingPopulation: 6.1,
    regions: [{ name: 'Nord' }, { name: 'Dar es Salaam' }, { name: 'Intérieur' }, { name: 'Sud' }],
    strengths: ['Safari & tourisme', 'Agriculture', 'Or'],
    weaknesses: ['Infrastructure', 'Eau rare en saison', 'Peu d\'industrie'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 10, agricultureBonus: 16 },
  },
  {
    id: 'w_sahara',
    name: 'Sahara occidental',
    flag: '🇪🇭',
    description: 'Sahara occidental — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 10, precious: 80, uranium: 0, ...food(5), water: 5 },
    startingMoney: 1500,
    startingPopulation: 0.1,
    regions: [{ name: 'Nord' }, { name: 'Sud' }],
    strengths: ['Phosphates', 'Pêche', 'Stabilité fragile'],
    weaknesses: ['Statut contesté', 'Désert', 'Population infime'],
    bonuses: { researchBonus: 2, militaryBonus: 5, tradeBonus: 6, agricultureBonus: 4 },
  },
  {
    id: 'kazakhstan',
    name: 'Kazakhstan',
    flag: '🇰🇿',
    description: 'Kazakhstan — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 70, iron: 35, coal: 25, rareEarths: 20, precious: 20, uranium: 12, ...food(40), water: 25 },
    startingMoney: 4800,
    startingPopulation: 1.9,
    regions: [{ name: 'Astana' }, { name: 'Almaty' }, { name: 'Ouest' }, { name: 'Est' }],
    strengths: ['Pétrole', 'Uranium', 'Mines', 'Agriculture'],
    weaknesses: ['Enclavé', 'Eau limitée', 'Dépendance énergie'],
    bonuses: { researchBonus: 7, militaryBonus: 10, tradeBonus: 10, agricultureBonus: 10 },
  },
  {
    id: 'uzbekistan',
    name: 'Ouzbékistan',
    flag: '🇺🇿',
    description: 'Ouzbékistan — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 15, iron: 5, coal: 5, rareEarths: 5, precious: 5, uranium: 2, ...food(55), water: 20 },
    startingMoney: 3000,
    startingPopulation: 3.5,
    regions: [{ name: 'Tachkent' }, { name: 'Samarcande' }, { name: 'Fergana' }],
    strengths: ['Coton', 'Or', 'Agriculture', 'Position silk road'],
    weaknesses: ['Eau Aral', 'Enclavé', 'Dépendance'],
    bonuses: { researchBonus: 6, militaryBonus: 8, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'papua_new_guinea',
    name: 'Papouasie-Nvl-Guinée',
    flag: '🇵🇬',
    description: 'Papouasie-Nvl-Guinée — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 15, iron: 15, coal: 5, rareEarths: 10, precious: 20, uranium: 2, ...food(60), water: 80 },
    startingMoney: 3000,
    startingPopulation: 1,
    regions: [{ name: 'Port Moresby' }, { name: 'Highlands' }, { name: 'Côte' }],
    strengths: ['Or', 'Cuivre', 'PNG LNG', 'Biodiversité'],
    weaknesses: ['Infrastructure nulle', 'Instabilité', 'Enclavé'],
    bonuses: { researchBonus: 4, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 12 },
  },
  {
    id: 'dem_rep_congo',
    name: 'RD Congo',
    flag: '🇨🇩',
    description: 'RD Congo — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 10, iron: 30, coal: 5, rareEarths: 25, precious: 15, uranium: 3, ...food(60), water: 80 },
    startingMoney: 2800,
    startingPopulation: 9.5,
    regions: [{ name: 'Kinshasa' }, { name: 'Est' }, { name: 'Nord' }, { name: 'Sud' }],
    strengths: ['Cobalt', 'Mines', 'Forêt tropicale', 'Eau'],
    weaknesses: ['Instabilité', 'Infrastructure', 'Corruption'],
    bonuses: { researchBonus: 4, militaryBonus: 10, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'somalia',
    name: 'Somalie',
    flag: '🇸🇴',
    description: 'Somalie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 10, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(25), water: 15 },
    startingMoney: 2200,
    startingPopulation: 1.7,
    regions: [{ name: 'Mogadiscio' }, { name: 'Centre' }, { name: 'Sud' }],
    strengths: ['Pêche', 'Bétail', 'Côte stratégique'],
    weaknesses: ['Instabilité politique', 'Sécheresse', 'Peu de ressources'],
    bonuses: { researchBonus: 3, militaryBonus: 10, tradeBonus: 8, agricultureBonus: 10 },
  },
  {
    id: 'sudan',
    name: 'Soudan',
    flag: '🇸🇩',
    description: 'Soudan — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 40, iron: 15, coal: 8, rareEarths: 5, precious: 8, uranium: 2, ...food(45), water: 30 },
    startingMoney: 2800,
    startingPopulation: 4.5,
    regions: [{ name: 'Khartoum' }, { name: 'Nord' }, { name: 'Est' }, { name: 'Sud' }],
    strengths: ['Pétrole', 'Agriculture du Nil', 'Bétail'],
    weaknesses: ['Instabilité', 'Sécheresse', 'Peu d\'industrie'],
    bonuses: { researchBonus: 4, militaryBonus: 12, tradeBonus: 8, agricultureBonus: 12 },
  },
  {
    id: 'chad',
    name: 'Tchad',
    flag: '🇹🇩',
    description: 'Tchad — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 30, iron: 5, coal: 2, rareEarths: 2, precious: 3, uranium: 0, ...food(30), water: 20 },
    startingMoney: 2300,
    startingPopulation: 1.7,
    regions: [{ name: 'N\'Djamena' }, { name: 'Nord' }, { name: 'Sud' }, { name: 'Est' }],
    strengths: ['Pétrole', 'Bétail', 'Uranium potentiel'],
    weaknesses: ['Enclavement', 'Désert', 'Instabilité'],
    bonuses: { researchBonus: 3, militaryBonus: 10, tradeBonus: 6, agricultureBonus: 12 },
  },
  {
    id: 'haiti',
    name: 'Haïti',
    flag: '🇭🇹',
    description: 'Haïti — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 2, precious: 3, uranium: 0, ...food(45), water: 35 },
    startingMoney: 2200,
    startingPopulation: 1.1,
    regions: [{ name: 'Port-au-Prince' }, { name: 'Nord' }],
    strengths: ['Agriculture', 'Textile émergent'],
    weaknesses: ['Catastrophes', 'Pauvreté', 'Infrastructure nulle'],
    bonuses: { researchBonus: 3, militaryBonus: 6, tradeBonus: 6, agricultureBonus: 14 },
  },
  {
    id: 'dominican_rep',
    name: 'Rép. Dominicaine',
    flag: '🇩🇴',
    description: 'Rép. Dominicaine — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 8, uranium: 0, ...food(60), water: 55 },
    startingMoney: 4000,
    startingPopulation: 1.1,
    regions: [{ name: 'Saint-Domingue' }, { name: 'Santiago' }],
    strengths: ['Tourisme', 'Or', 'Agriculture', 'Zones franches'],
    weaknesses: ['Inégalités', 'Énergie', 'Dépendance imports'],
    bonuses: { researchBonus: 7, militaryBonus: 5, tradeBonus: 14, agricultureBonus: 12 },
  },
  {
    id: 'bahamas',
    name: 'Bahamas',
    flag: '🇧🇸',
    description: 'Bahamas — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 2, coal: 1, rareEarths: 1, precious: 2, uranium: 0, ...food(30), water: 50 },
    startingMoney: 6000,
    startingPopulation: 0.04,
    regions: [{ name: 'Nassau' }, { name: 'Grand Bahama' }],
    strengths: ['Tourisme', 'Finance offshore'],
    weaknesses: ['Petit', 'Ouragan', 'Peu de ressources'],
    bonuses: { researchBonus: 5, militaryBonus: 4, tradeBonus: 18, agricultureBonus: 6 },
  },
  {
    id: 'falkland_is',
    name: 'Îles Malouines',
    flag: '🇫🇰',
    description: 'Îles Malouines — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 2, coal: 1, rareEarths: 2, precious: 2, uranium: 0, ...food(20), water: 60 },
    startingMoney: 5000,
    startingPopulation: 0.003,
    regions: [{ name: 'Stanley' }, { name: 'Intérieur' }],
    strengths: ['Pêche', 'Élevage ovin', 'Pétrole potentiel'],
    weaknesses: ['Très petit', 'Isolé', 'Revendication Argentine'],
    bonuses: { researchBonus: 5, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 8 },
  },
  {
    id: 'greenland',
    name: 'Groenland',
    flag: '🇬🇱',
    description: 'Groenland — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 10, coal: 5, rareEarths: 10, precious: 10, uranium: 5, ...food(10), water: 80 },
    startingMoney: 5500,
    startingPopulation: 0.06,
    regions: [{ name: 'Nuuk' }, { name: 'Nord' }, { name: 'Est' }, { name: 'Ouest' }],
    strengths: ['Minerais arctiques', 'Pêche', 'Potentiel énergétique'],
    weaknesses: ['Population infime', 'Glace', 'Dépendance Danemark'],
    bonuses: { researchBonus: 6, militaryBonus: 4, tradeBonus: 8, agricultureBonus: 4 },
  },
  {
    id: 'fr_s_antarctic_lands',
    name: 'T.A.A.F.',
    flag: '🇹🇫',
    description: 'T.A.A.F. — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 2, coal: 1, rareEarths: 3, precious: 3, uranium: 0, ...food(5), water: 50 },
    startingMoney: 1000,
    startingPopulation: 0.001,
    regions: [{ name: 'Kerguelen' }, { name: 'Crozet' }],
    strengths: ['Pêche', 'Recherche scientifique'],
    weaknesses: ['Inhabité', 'Isolé', 'Pas d\'économie'],
    bonuses: { researchBonus: 5, militaryBonus: 2, tradeBonus: 4, agricultureBonus: 2 },
  },
  {
    id: 'timor_leste',
    name: 'Timor-Leste',
    flag: '🇹🇱',
    description: 'Timor-Leste — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 20, iron: 3, coal: 2, rareEarths: 2, precious: 3, uranium: 0, ...food(50), water: 50 },
    startingMoney: 3000,
    startingPopulation: 0.1,
    regions: [{ name: 'Dili' }, { name: 'Intérieur' }],
    strengths: ['Pétrole offshore', 'Agriculture', 'Café'],
    weaknesses: ['Très petit', 'Post-conflit', 'Infrastructure'],
    bonuses: { researchBonus: 4, militaryBonus: 5, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'lesotho',
    name: 'Lesotho',
    flag: '🇱🇸',
    description: 'Lesotho — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 2, precious: 8, uranium: 0, ...food(40), water: 70 },
    startingMoney: 2500,
    startingPopulation: 0.2,
    regions: [{ name: 'Maseru' }, { name: 'Montagnes' }],
    strengths: ['Eau (Lesotho Highlands)', 'Diamants', 'Laine'],
    weaknesses: ['Enclavé', 'Montagneux', 'Économie faible'],
    bonuses: { researchBonus: 4, militaryBonus: 5, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'uruguay',
    name: 'Uruguay',
    flag: '🇺🇾',
    description: 'Uruguay — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 3, iron: 5, coal: 2, rareEarths: 3, precious: 3, uranium: 0, ...food(75), water: 65 },
    startingMoney: 4500,
    startingPopulation: 0.3,
    regions: [{ name: 'Montevideo' }, { name: 'Intérieur' }],
    strengths: ['Agriculture', 'Bœuf', 'Stabilité', 'Énergies verte'],
    weaknesses: ['Petit', 'Peu de minerais', 'Dépendance'],
    bonuses: { researchBonus: 10, militaryBonus: 5, tradeBonus: 14, agricultureBonus: 18 },
  },
  {
    id: 'bolivia',
    name: 'Bolivie',
    flag: '🇧🇴',
    description: 'Bolivie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 20, iron: 10, coal: 5, rareEarths: 25, precious: 15, uranium: 5, ...food(55), water: 60 },
    startingMoney: 3000,
    startingPopulation: 1.2,
    regions: [{ name: 'La Paz' }, { name: 'Santa Cruz' }, { name: 'Potosí' }, { name: 'Oriente' }],
    strengths: ['Lithium', 'Gaz', 'Agriculture', 'Mines'],
    weaknesses: ['Enclavé', 'Infrastructure', 'Pauvreté'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 12 },
  },
  {
    id: 'panama',
    name: 'Panama',
    flag: '🇵🇦',
    description: 'Panama — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(45), water: 65 },
    startingMoney: 5000,
    startingPopulation: 0.4,
    regions: [{ name: 'Panama City' }, { name: 'Intérieur' }],
    strengths: ['Canal', 'Finance', 'Commerce mondial'],
    weaknesses: ['Peu de ressources', 'Inégalités', 'Dépendance'],
    bonuses: { researchBonus: 8, militaryBonus: 5, tradeBonus: 20, agricultureBonus: 8 },
  },
  {
    id: 'costa_rica',
    name: 'Costa Rica',
    flag: '🇨🇷',
    description: 'Costa Rica — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 3, uranium: 0, ...food(60), water: 75 },
    startingMoney: 4500,
    startingPopulation: 0.5,
    regions: [{ name: 'San José' }, { name: 'Provinces' }],
    strengths: ['Tourisme', 'Agriculture', 'Énergies vertes'],
    weaknesses: ['Peu de minerais', 'Infrastructure', 'Coûts élevés'],
    bonuses: { researchBonus: 10, militaryBonus: 4, tradeBonus: 14, agricultureBonus: 16 },
  },
  {
    id: 'nicaragua',
    name: 'Nicaragua',
    flag: '🇳🇮',
    description: 'Nicaragua — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 3, uranium: 0, ...food(60), water: 65 },
    startingMoney: 2800,
    startingPopulation: 0.7,
    regions: [{ name: 'Managua' }, { name: 'Est' }],
    strengths: ['Agriculture', 'Pêche', 'Canaux potentiels'],
    weaknesses: ['Pauvreté', 'Infrastructure', 'Instabilité'],
    bonuses: { researchBonus: 4, militaryBonus: 7, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'honduras',
    name: 'Honduras',
    flag: '🇭🇳',
    description: 'Honduras — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 8, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(55), water: 60 },
    startingMoney: 2800,
    startingPopulation: 1,
    regions: [{ name: 'Tegucigalpa' }, { name: 'Côte Nord' }],
    strengths: ['Agriculture', 'Mines', 'Pêche'],
    weaknesses: ['Violence', 'Corruption', 'Infrastructure'],
    bonuses: { researchBonus: 4, militaryBonus: 7, tradeBonus: 8, agricultureBonus: 12 },
  },
  {
    id: 'el_salvador',
    name: 'El Salvador',
    flag: '🇸🇻',
    description: 'El Salvador — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 3, coal: 2, rareEarths: 2, precious: 3, uranium: 0, ...food(55), water: 50 },
    startingMoney: 3000,
    startingPopulation: 0.6,
    regions: [{ name: 'San Salvador' }, { name: 'Intérieur' }],
    strengths: ['Agriculture', 'Café', 'Géothermie'],
    weaknesses: ['Très petit', 'Violence', 'Peu de ressources'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'guatemala',
    name: 'Guatemala',
    flag: '🇬🇹',
    description: 'Guatemala — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(65), water: 60 },
    startingMoney: 3200,
    startingPopulation: 1.7,
    regions: [{ name: 'Guatemala City' }, { name: 'Intérieur' }],
    strengths: ['Café', 'Cardamome', 'Pétrole', 'Mines'],
    weaknesses: ['Inégalités', 'Infrastructure', 'Violence'],
    bonuses: { researchBonus: 5, militaryBonus: 7, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'belize',
    name: 'Belize',
    flag: '🇧🇿',
    description: 'Belize — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 2, coal: 1, rareEarths: 2, precious: 2, uranium: 0, ...food(50), water: 65 },
    startingMoney: 3500,
    startingPopulation: 0.04,
    regions: [{ name: 'Belmopan' }, { name: 'Côte' }],
    strengths: ['Tourisme', 'Agriculture', 'Pêche'],
    weaknesses: ['Très petit', 'Infrastructure', 'Peu de ressources'],
    bonuses: { researchBonus: 6, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 12 },
  },
  {
    id: 'venezuela',
    name: 'Venezuela',
    flag: '🇻🇪',
    description: 'Venezuela — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 95, iron: 15, coal: 5, rareEarths: 8, precious: 15, uranium: 2, ...food(50), water: 70 },
    startingMoney: 3200,
    startingPopulation: 2.9,
    regions: [{ name: 'Caracas' }, { name: 'Maracaibo' }, { name: 'Orénoque' }, { name: 'Amazonas' }],
    strengths: ['Pétrole immense', 'Eau', 'Biodiversité'],
    weaknesses: ['Crise économique', 'Inflation', 'Instabilité'],
    bonuses: { researchBonus: 5, militaryBonus: 10, tradeBonus: 8, agricultureBonus: 12 },
  },
  {
    id: 'guyana',
    name: 'Guyana',
    flag: '🇬🇾',
    description: 'Guyana — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 40, iron: 5, coal: 2, rareEarths: 3, precious: 10, uranium: 2, ...food(55), water: 80 },
    startingMoney: 4000,
    startingPopulation: 0.08,
    regions: [{ name: 'Georgetown' }, { name: 'Intérieur' }, { name: 'Côte' }],
    strengths: ['Pétrole offshore', 'Or', 'Sucre', 'Bois'],
    weaknesses: ['Post-pauvreté', 'Infrastructure', 'Petit'],
    bonuses: { researchBonus: 6, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 12 },
  },
  {
    id: 'suriname',
    name: 'Suriname',
    flag: '🇸🇷',
    description: 'Suriname — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 15, iron: 5, coal: 2, rareEarths: 5, precious: 10, uranium: 0, ...food(55), water: 80 },
    startingMoney: 3800,
    startingPopulation: 0.06,
    regions: [{ name: 'Paramaribo' }, { name: 'Intérieur' }],
    strengths: ['Or', 'Bauxite', 'Bois', 'Sucre'],
    weaknesses: ['Infrastructure', 'Petit', 'Dépendance'],
    bonuses: { researchBonus: 5, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 12 },
  },
  {
    id: 'ecuador',
    name: 'Équateur',
    flag: '🇪🇨',
    description: 'Équateur — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 40, iron: 5, coal: 2, rareEarths: 8, precious: 10, uranium: 2, ...food(70), water: 70 },
    startingMoney: 3500,
    startingPopulation: 1.8,
    regions: [{ name: 'Quito' }, { name: 'Côte Pacifique' }, { name: 'Amazonie' }],
    strengths: ['Pétrole', 'Bananes', 'Cacao', 'Pêche'],
    weaknesses: ['Dépendance pétrole', 'Infrastructure', 'Inégalités'],
    bonuses: { researchBonus: 6, militaryBonus: 7, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'puerto_rico',
    name: 'Porto Rico',
    flag: '🇵🇷',
    description: 'Porto Rico — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 3, coal: 1, rareEarths: 2, precious: 2, uranium: 0, ...food(45), water: 50 },
    startingMoney: 4500,
    startingPopulation: 0.3,
    regions: [{ name: 'San Juan' }, { name: 'Ouest' }],
    strengths: ['Pharma', 'Tourisme', 'Agriculture'],
    weaknesses: ['Statut (territoire USA)', 'Dette', 'Dépendance'],
    bonuses: { researchBonus: 9, militaryBonus: 4, tradeBonus: 12, agricultureBonus: 10 },
  },
  {
    id: 'jamaica',
    name: 'Jamaïque',
    flag: '🇯🇲',
    description: 'Jamaïque — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 2, precious: 5, uranium: 0, ...food(55), water: 55 },
    startingMoney: 3500,
    startingPopulation: 0.3,
    regions: [{ name: 'Kingston' }, { name: 'Parishes' }],
    strengths: ['Tourisme', 'Bauxite', 'Agriculture'],
    weaknesses: ['Petite', 'Peu de ressources', 'Dette'],
    bonuses: { researchBonus: 6, militaryBonus: 5, tradeBonus: 12, agricultureBonus: 12 },
  },
  {
    id: 'cuba',
    name: 'Cuba',
    flag: '🇨🇺',
    description: 'Cuba — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 15, iron: 5, coal: 2, rareEarths: 5, precious: 5, uranium: 0, ...food(60), water: 50 },
    startingMoney: 2800,
    startingPopulation: 1.1,
    regions: [{ name: 'La Havane' }, { name: 'Orient' }],
    strengths: ['Nickel', 'Tourisme', 'Médecine', 'Agriculture'],
    weaknesses: ['Sanctions', 'Économie fermée', 'Peu d\'industrie'],
    bonuses: { researchBonus: 8, militaryBonus: 8, tradeBonus: 6, agricultureBonus: 14 },
  },
  {
    id: 'zimbabwe',
    name: 'Zimbabwe',
    flag: '🇿🇼',
    description: 'Zimbabwe — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 15, coal: 8, rareEarths: 8, precious: 12, uranium: 2, ...food(50), water: 35 },
    startingMoney: 2800,
    startingPopulation: 1.6,
    regions: [{ name: 'Harare' }, { name: 'Bulawayo' }, { name: 'Nord' }],
    strengths: ['Platine', 'Chrome', 'Agriculture passée'],
    weaknesses: ['Inflation', 'Instabilité', 'Infrastructure'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 12 },
  },
  {
    id: 'botswana',
    name: 'Botswana',
    flag: '🇧🇼',
    description: 'Botswana — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 3, rareEarths: 3, precious: 30, uranium: 0, ...food(25), water: 20 },
    startingMoney: 4200,
    startingPopulation: 0.3,
    regions: [{ name: 'Gaborone' }, { name: 'Désert' }, { name: 'Nord' }],
    strengths: ['Diamants', 'Stabilité', 'Tourisme safari'],
    weaknesses: ['Eau très limitée', 'Économie mono-produit', 'Enclavement'],
    bonuses: { researchBonus: 8, militaryBonus: 5, tradeBonus: 14, agricultureBonus: 6 },
  },
  {
    id: 'namibia',
    name: 'Namibie',
    flag: '🇳🇦',
    description: 'Namibie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 10, coal: 5, rareEarths: 5, precious: 20, uranium: 3, ...food(20), water: 15 },
    startingMoney: 4000,
    startingPopulation: 0.3,
    regions: [{ name: 'Windhoek' }, { name: 'Nord' }, { name: 'Côte' }, { name: 'Sud' }],
    strengths: ['Diamants', 'Uranium', 'Pêche', 'Tourisme'],
    weaknesses: ['Eau critique', 'Population très faible', 'Désert'],
    bonuses: { researchBonus: 7, militaryBonus: 6, tradeBonus: 12, agricultureBonus: 6 },
  },
  {
    id: 'senegal',
    name: 'Sénégal',
    flag: '🇸🇳',
    description: 'Sénégal — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 10, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(55), water: 40 },
    startingMoney: 3000,
    startingPopulation: 1.7,
    regions: [{ name: 'Dakar' }, { name: 'Intérieur' }],
    strengths: ['Phosphates', 'Pêche', 'Stabilité'],
    weaknesses: ['Peu de pétrole', 'Sécheresse', 'Pauvreté'],
    bonuses: { researchBonus: 7, militaryBonus: 5, tradeBonus: 12, agricultureBonus: 14 },
  },
  {
    id: 'mali',
    name: 'Mali',
    flag: '🇲🇱',
    description: 'Mali — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 8, coal: 2, rareEarths: 3, precious: 12, uranium: 2, ...food(30), water: 30 },
    startingMoney: 2500,
    startingPopulation: 2.2,
    regions: [{ name: 'Bamako' }, { name: 'Nord' }, { name: 'Sahara' }, { name: 'Sahel' }],
    strengths: ['Or', 'Coton', 'Uranium potentiel'],
    weaknesses: ['Désert', 'Instabilité', 'Enclavement'],
    bonuses: { researchBonus: 3, militaryBonus: 10, tradeBonus: 6, agricultureBonus: 10 },
  },
  {
    id: 'mauritania',
    name: 'Mauritanie',
    flag: '🇲🇷',
    description: 'Mauritanie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 15, iron: 30, coal: 5, rareEarths: 3, precious: 8, uranium: 0, ...food(15), water: 10 },
    startingMoney: 2800,
    startingPopulation: 0.5,
    regions: [{ name: 'Nouakchott' }, { name: 'Intérieur' }, { name: 'Nord' }, { name: 'Côte' }],
    strengths: ['Fer', 'Pêche', 'Or', 'Pétrole émergent'],
    weaknesses: ['Désert', 'Eau critique', 'Population faible'],
    bonuses: { researchBonus: 4, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 6 },
  },
  {
    id: 'benin',
    name: 'Bénin',
    flag: '🇧🇯',
    description: 'Bénin — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 3, coal: 2, rareEarths: 2, precious: 3, uranium: 0, ...food(55), water: 45 },
    startingMoney: 2500,
    startingPopulation: 1.2,
    regions: [{ name: 'Cotonou' }, { name: 'Nord' }],
    strengths: ['Agriculture', 'Commerce informel', 'Coton'],
    weaknesses: ['Peu d\'industrie', 'Instabilité', 'Infrastructure'],
    bonuses: { researchBonus: 4, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'niger',
    name: 'Niger',
    flag: '🇳🇪',
    description: 'Niger — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 2, rareEarths: 5, precious: 8, uranium: 25, ...food(25), water: 20 },
    startingMoney: 2300,
    startingPopulation: 2.5,
    regions: [{ name: 'Niamey' }, { name: 'Désert Nord' }, { name: 'Est' }, { name: 'Sahel' }],
    strengths: ['Uranium', 'Or', 'Bétail'],
    weaknesses: ['Sécheresse', 'Enclavement', 'Pauvreté'],
    bonuses: { researchBonus: 3, militaryBonus: 8, tradeBonus: 6, agricultureBonus: 10 },
  },
  {
    id: 'cameroon',
    name: 'Cameroun',
    flag: '🇨🇲',
    description: 'Cameroun — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 25, iron: 10, coal: 5, rareEarths: 5, precious: 8, uranium: 0, ...food(60), water: 60 },
    startingMoney: 3200,
    startingPopulation: 2.8,
    regions: [{ name: 'Yaoundé' }, { name: 'Douala' }, { name: 'Nord' }],
    strengths: ['Pétrole', 'Cacao', 'Bois'],
    weaknesses: ['Corruption', 'Infrastructure', 'Instabilité'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'togo',
    name: 'Togo',
    flag: '🇹🇬',
    description: 'Togo — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 8, uranium: 0, ...food(55), water: 50 },
    startingMoney: 2500,
    startingPopulation: 0.8,
    regions: [{ name: 'Lomé' }, { name: 'Nord' }],
    strengths: ['Phosphates', 'Agriculture', 'Port'],
    weaknesses: ['Peu de ressources', 'Enclavement', 'Pauvreté'],
    bonuses: { researchBonus: 5, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'ghana',
    name: 'Ghana',
    flag: '🇬🇭',
    description: 'Ghana — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 25, iron: 15, coal: 5, rareEarths: 5, precious: 10, uranium: 0, ...food(60), water: 50 },
    startingMoney: 3500,
    startingPopulation: 3.2,
    regions: [{ name: 'Accra' }, { name: 'Centre' }, { name: 'Nord' }],
    strengths: ['Or', 'Cacao', 'Pétrole', 'Stabilité'],
    weaknesses: ['Infrastructure', 'Endettement', 'Énergie'],
    bonuses: { researchBonus: 8, militaryBonus: 7, tradeBonus: 12, agricultureBonus: 14 },
  },
  {
    id: 'c_te_d_ivoire',
    name: 'Côte d\'Ivoire',
    flag: '🇨🇮',
    description: 'Côte d\'Ivoire — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 10, iron: 8, coal: 2, rareEarths: 5, precious: 8, uranium: 0, ...food(70), water: 55 },
    startingMoney: 3500,
    startingPopulation: 2.7,
    regions: [{ name: 'Abidjan' }, { name: 'Centre' }, { name: 'Nord' }],
    strengths: ['Cacao mondial', 'Caoutchouc', 'Commerce'],
    weaknesses: ['Agriculture fragile', 'Instabilité', 'Inégalités'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 14, agricultureBonus: 16 },
  },
  {
    id: 'guinea',
    name: 'Guinée',
    flag: '🇬🇳',
    description: 'Guinée — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 30, coal: 5, rareEarths: 5, precious: 8, uranium: 0, ...food(60), water: 70 },
    startingMoney: 2800,
    startingPopulation: 1.4,
    regions: [{ name: 'Conakry' }, { name: 'Intérieur' }, { name: 'Nord' }],
    strengths: ['Bauxite mondiale', 'Or', 'Agriculture'],
    weaknesses: ['Infrastructure', 'Instabilité', 'Peu d\'industrie'],
    bonuses: { researchBonus: 4, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'guinea_bissau',
    name: 'Guinée-Bissau',
    flag: '🇬🇼',
    description: 'Guinée-Bissau — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 2, coal: 1, rareEarths: 2, precious: 2, uranium: 0, ...food(50), water: 40 },
    startingMoney: 2200,
    startingPopulation: 0.2,
    regions: [{ name: 'Bissau' }, { name: 'Intérieur' }],
    strengths: ['Noix de cajou', 'Pêche'],
    weaknesses: ['Instabilité', 'Peu de ressources', 'Enclavé'],
    bonuses: { researchBonus: 3, militaryBonus: 5, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'liberia',
    name: 'Libéria',
    flag: '🇱🇷',
    description: 'Libéria — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 10, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(55), water: 75 },
    startingMoney: 2500,
    startingPopulation: 0.5,
    regions: [{ name: 'Monrovia' }, { name: 'Intérieur' }],
    strengths: ['Fer', 'Caoutchouc', 'Bois'],
    weaknesses: ['Post-conflit', 'Infrastructure', 'Corruption'],
    bonuses: { researchBonus: 4, militaryBonus: 5, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'sierra_leone',
    name: 'Sierra Leone',
    flag: '🇸🇱',
    description: 'Sierra Leone — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 5, precious: 15, uranium: 0, ...food(50), water: 70 },
    startingMoney: 2500,
    startingPopulation: 0.8,
    regions: [{ name: 'Freetown' }, { name: 'Intérieur' }],
    strengths: ['Diamants', 'Fer', 'Agriculture'],
    weaknesses: ['Post-conflit', 'Infrastructure', 'Pauvreté'],
    bonuses: { researchBonus: 4, militaryBonus: 5, tradeBonus: 8, agricultureBonus: 12 },
  },
  {
    id: 'burkina_faso',
    name: 'Burkina Faso',
    flag: '🇧🇫',
    description: 'Burkina Faso — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 2, precious: 10, uranium: 0, ...food(50), water: 35 },
    startingMoney: 2500,
    startingPopulation: 2.2,
    regions: [{ name: 'Ouagadougou' }, { name: 'Sahel' }, { name: 'Sud' }],
    strengths: ['Or', 'Coton', 'Bétail'],
    weaknesses: ['Enclavement', 'Sécheresse', 'Instabilité'],
    bonuses: { researchBonus: 4, militaryBonus: 7, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'central_african_rep',
    name: 'Centrafrique',
    flag: '🇨🇫',
    description: 'Centrafrique — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 5, precious: 15, uranium: 2, ...food(45), water: 55 },
    startingMoney: 2200,
    startingPopulation: 0.5,
    regions: [{ name: 'Bangui' }, { name: 'Nord' }, { name: 'Sud' }],
    strengths: ['Diamants', 'Or', 'Bois'],
    weaknesses: ['Instabilité grave', 'Enclavement', 'Pauvreté'],
    bonuses: { researchBonus: 3, militaryBonus: 8, tradeBonus: 6, agricultureBonus: 12 },
  },
  {
    id: 'congo',
    name: 'République du Congo',
    flag: '🇨🇬',
    description: 'République du Congo — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 40, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(45), water: 70 },
    startingMoney: 3800,
    startingPopulation: 0.6,
    regions: [{ name: 'Brazzaville' }, { name: 'Pointe-Noire' }, { name: 'Nord' }],
    strengths: ['Pétrole', 'Bois', 'Agriculture'],
    weaknesses: ['Corruption', 'Infrastructure', 'Dépendance pétrole'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 10, agricultureBonus: 10 },
  },
  {
    id: 'gabon',
    name: 'Gabon',
    flag: '🇬🇦',
    description: 'Gabon — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 45, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(40), water: 70 },
    startingMoney: 5000,
    startingPopulation: 0.2,
    regions: [{ name: 'Libreville' }, { name: 'Centre' }, { name: 'Sud' }],
    strengths: ['Pétrole', 'Manganèse', 'Bois tropical'],
    weaknesses: ['Population faible', 'Post-pétrole', 'Inégalités'],
    bonuses: { researchBonus: 7, militaryBonus: 7, tradeBonus: 12, agricultureBonus: 8 },
  },
  {
    id: 'eq_guinea',
    name: 'Guinée équatoriale',
    flag: '🇬🇶',
    description: 'Guinée équatoriale — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 50, iron: 5, coal: 2, rareEarths: 2, precious: 5, uranium: 0, ...food(35), water: 55 },
    startingMoney: 6000,
    startingPopulation: 0.2,
    regions: [{ name: 'Malabo' }, { name: 'Bata' }],
    strengths: ['Pétrole offshore', 'Capital élevé'],
    weaknesses: ['Population minuscule', 'Corruption', 'Post-pétrole'],
    bonuses: { researchBonus: 4, militaryBonus: 6, tradeBonus: 10, agricultureBonus: 6 },
  },
  {
    id: 'zambia',
    name: 'Zambie',
    flag: '🇿🇲',
    description: 'Zambie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 3, iron: 20, coal: 10, rareEarths: 5, precious: 15, uranium: 2, ...food(50), water: 60 },
    startingMoney: 2800,
    startingPopulation: 1.9,
    regions: [{ name: 'Lusaka' }, { name: 'Copperbelt' }, { name: 'Nord' }],
    strengths: ['Cuivre', 'Eau douce', 'Agriculture'],
    weaknesses: ['Enclavement', 'Dépendance minière', 'Pauvreté'],
    bonuses: { researchBonus: 5, militaryBonus: 7, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'malawi',
    name: 'Malawi',
    flag: '🇲🇼',
    description: 'Malawi — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(55), water: 60 },
    startingMoney: 2300,
    startingPopulation: 2,
    regions: [{ name: 'Lilongwe' }, { name: 'Lac Malawi' }],
    strengths: ['Agriculture', 'Lac', 'Tabac'],
    weaknesses: ['Enclavement', 'Peu de ressources', 'Pauvreté'],
    bonuses: { researchBonus: 4, militaryBonus: 5, tradeBonus: 8, agricultureBonus: 16 },
  },
  {
    id: 'mozambique',
    name: 'Mozambique',
    flag: '🇲🇿',
    description: 'Mozambique — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 15, iron: 10, coal: 20, rareEarths: 5, precious: 8, uranium: 0, ...food(55), water: 50 },
    startingMoney: 2800,
    startingPopulation: 3.2,
    regions: [{ name: 'Maputo' }, { name: 'Centre' }, { name: 'Nord' }, { name: 'Zambèze' }],
    strengths: ['Gaz naturel', 'Agriculture', 'Côte Indienne'],
    weaknesses: ['Pauvreté', 'Cyclones', 'Infrastructure faible'],
    bonuses: { researchBonus: 4, militaryBonus: 7, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'eswatini',
    name: 'Eswatini',
    flag: '🇸🇿',
    description: 'Eswatini — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(45), water: 40 },
    startingMoney: 3000,
    startingPopulation: 0.1,
    regions: [{ name: 'Mbabane' }, { name: 'Manzini' }],
    strengths: ['Agriculture', 'Sucre', 'Stabilité'],
    weaknesses: ['Enclavé dans Afrique du Sud', 'Peu d\'industrie'],
    bonuses: { researchBonus: 5, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'angola',
    name: 'Angola',
    flag: '🇦🇴',
    description: 'Angola — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 65, iron: 15, coal: 8, rareEarths: 8, precious: 12, uranium: 2, ...food(45), water: 40 },
    startingMoney: 3500,
    startingPopulation: 3.4,
    regions: [{ name: 'Luanda' }, { name: 'Nord' }, { name: 'Centre' }, { name: 'Sud' }],
    strengths: ['Pétrole offshore', 'Diamants', 'Bois tropical'],
    weaknesses: ['Corruption', 'Infrastructure', 'Eau limitée'],
    bonuses: { researchBonus: 5, militaryBonus: 10, tradeBonus: 10, agricultureBonus: 10 },
  },
  {
    id: 'burundi',
    name: 'Burundi',
    flag: '🇧🇮',
    description: 'Burundi — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(55), water: 50 },
    startingMoney: 2200,
    startingPopulation: 1.3,
    regions: [{ name: 'Bujumbura' }, { name: 'Est' }],
    strengths: ['Agriculture', 'Café', 'Lac Tanganyika'],
    weaknesses: ['Instabilité', 'Surpopulation', 'Peu de ressources'],
    bonuses: { researchBonus: 3, militaryBonus: 8, tradeBonus: 6, agricultureBonus: 16 },
  },
  {
    id: 'lebanon',
    name: 'Liban',
    flag: '🇱🇧',
    description: 'Liban — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 2, rareEarths: 5, precious: 5, uranium: 0, ...food(45), water: 30 },
    startingMoney: 3000,
    startingPopulation: 0.7,
    regions: [{ name: 'Beyrouth' }, { name: 'Intérieur' }],
    strengths: ['Services bancaires', 'Diaspora', 'Agriculture'],
    weaknesses: ['Crise économique', 'Instabilité', 'Peu de ressources'],
    bonuses: { researchBonus: 9, militaryBonus: 5, tradeBonus: 14, agricultureBonus: 10 },
  },
  {
    id: 'madagascar',
    name: 'Madagascar',
    flag: '🇲🇬',
    description: 'Madagascar — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 2, iron: 10, coal: 2, rareEarths: 15, precious: 15, uranium: 0, ...food(55), water: 55 },
    startingMoney: 2500,
    startingPopulation: 2.7,
    regions: [{ name: 'Nord' }, { name: 'Centre' }, { name: 'Sud' }],
    strengths: ['Vanille', 'Nickel', 'Biodiversité'],
    weaknesses: ['Infrastructure', 'Cyclones', 'Pauvreté'],
    bonuses: { researchBonus: 5, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 16 },
  },
  {
    id: 'gambia',
    name: 'Gambie',
    flag: '🇬🇲',
    description: 'Gambie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 2, coal: 1, rareEarths: 1, precious: 2, uranium: 0, ...food(45), water: 40 },
    startingMoney: 2500,
    startingPopulation: 0.2,
    regions: [{ name: 'Banjul' }, { name: 'Intérieur' }],
    strengths: ['Tourisme', 'Arachides', 'Pêche'],
    weaknesses: ['Enclavement', 'Très petit', 'Peu de ressources'],
    bonuses: { researchBonus: 4, militaryBonus: 4, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'jordan',
    name: 'Jordanie',
    flag: '🇯🇴',
    description: 'Jordanie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 3, rareEarths: 3, precious: 8, uranium: 2, ...food(30), water: 20 },
    startingMoney: 3500,
    startingPopulation: 1,
    regions: [{ name: 'Amman' }, { name: 'Aqaba' }],
    strengths: ['Position stratégique', 'Phosphates', 'Stabilité'],
    weaknesses: ['Quasi pas de pétrole', 'Eau critique', 'Dépendance aid'],
    bonuses: { researchBonus: 8, militaryBonus: 8, tradeBonus: 12, agricultureBonus: 8 },
  },
  {
    id: 'united_arab_emirates',
    name: 'Émirats arabes unis',
    flag: '🇦🇪',
    description: 'Émirats arabes unis — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 90, iron: 5, coal: 2, rareEarths: 3, precious: 10, uranium: 0, ...food(5), water: 5 },
    startingMoney: 8000,
    startingPopulation: 1,
    regions: [{ name: 'Abu Dhabi' }, { name: 'Dubaï' }],
    strengths: ['Pétrole', 'Finance', 'Hub mondial', 'Logistique'],
    weaknesses: ['Eau critique', 'Dépendance pétrole', 'Population importée'],
    bonuses: { researchBonus: 7, militaryBonus: 8, tradeBonus: 22, agricultureBonus: 2 },
  },
  {
    id: 'qatar',
    name: 'Qatar',
    flag: '🇶🇦',
    description: 'Qatar — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 80, iron: 3, coal: 2, rareEarths: 2, precious: 5, uranium: 0, ...food(5), water: 5 },
    startingMoney: 9000,
    startingPopulation: 0.3,
    regions: [{ name: 'Doha' }, { name: 'Intérieur' }],
    strengths: ['Gaz naturel', 'Finance', 'Hub'],
    weaknesses: ['Eau critique', 'Population infime', 'Dépendance'],
    bonuses: { researchBonus: 6, militaryBonus: 7, tradeBonus: 20, agricultureBonus: 2 },
  },
  {
    id: 'kuwait',
    name: 'Koweït',
    flag: '🇰🇼',
    description: 'Koweït — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 90, iron: 3, coal: 2, rareEarths: 2, precious: 5, uranium: 0, ...food(5), water: 5 },
    startingMoney: 9000,
    startingPopulation: 0.4,
    regions: [{ name: 'Koweït City' }, { name: 'Al Ahmadi' }],
    strengths: ['Pétrole immense', 'Fonds souverain', 'Finance'],
    weaknesses: ['Eau nulle', 'Agriculture nulle', 'Petit'],
    bonuses: { researchBonus: 5, militaryBonus: 7, tradeBonus: 20, agricultureBonus: 2 },
  },
  {
    id: 'oman',
    name: 'Oman',
    flag: '🇴🇲',
    description: 'Oman — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 55, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 2, ...food(10), water: 15 },
    startingMoney: 5000,
    startingPopulation: 0.5,
    regions: [{ name: 'Mascate' }, { name: 'Dhofar' }, { name: 'Intérieur' }],
    strengths: ['Pétrole', 'Gaz', 'Position maritime'],
    weaknesses: ['Eau limitée', 'Post-pétrole', 'Agriculture nulle'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 14, agricultureBonus: 4 },
  },
  {
    id: 'vanuatu',
    name: 'Vanuatu',
    flag: '🇻🇺',
    description: 'Vanuatu — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 2, coal: 1, rareEarths: 2, precious: 2, uranium: 0, ...food(50), water: 70 },
    startingMoney: 3000,
    startingPopulation: 0.03,
    regions: [{ name: 'Port Vila' }, { name: 'Santo' }],
    strengths: ['Agriculture', 'Tourisme', 'Pêche'],
    weaknesses: ['Vulcans', 'Isolé', 'Petit'],
    bonuses: { researchBonus: 4, militaryBonus: 4, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'cambodia',
    name: 'Cambodge',
    flag: '🇰🇭',
    description: 'Cambodge — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 2, rareEarths: 3, precious: 3, uranium: 0, ...food(65), water: 60 },
    startingMoney: 2800,
    startingPopulation: 1.7,
    regions: [{ name: 'Phnom Penh' }, { name: 'Provinces' }],
    strengths: ['Riz', 'Tourisme Angkor', 'Textile'],
    weaknesses: ['Peu d\'industrie', 'Infrastructure', 'Corruption'],
    bonuses: { researchBonus: 5, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 16 },
  },
  {
    id: 'laos',
    name: 'Laos',
    flag: '🇱🇦',
    description: 'Laos — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 10, coal: 5, rareEarths: 5, precious: 5, uranium: 0, ...food(65), water: 70 },
    startingMoney: 2800,
    startingPopulation: 0.7,
    regions: [{ name: 'Vientiane' }, { name: 'Nord' }, { name: 'Sud' }],
    strengths: ['Hydroélectricité', 'Mines', 'Agriculture'],
    weaknesses: ['Enclavé', 'Pauvreté', 'Infrastructure'],
    bonuses: { researchBonus: 5, militaryBonus: 6, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'myanmar',
    name: 'Myanmar',
    flag: '🇲🇲',
    description: 'Myanmar — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 10, iron: 20, coal: 8, rareEarths: 10, precious: 15, uranium: 2, ...food(70), water: 65 },
    startingMoney: 2800,
    startingPopulation: 5.4,
    regions: [{ name: 'Yangon' }, { name: 'Mandalay' }, { name: 'Nord' }],
    strengths: ['Jade', 'Rubis', 'Agriculture', 'Bois'],
    weaknesses: ['Instabilité', 'Sanctions', 'Peu d\'industrie'],
    bonuses: { researchBonus: 4, militaryBonus: 10, tradeBonus: 8, agricultureBonus: 16 },
  },
  {
    id: 'north_korea',
    name: 'Corée du Nord',
    flag: '🇰🇵',
    description: 'Corée du Nord — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 20, coal: 25, rareEarths: 10, precious: 5, uranium: 5, ...food(35), water: 40 },
    startingMoney: 2000,
    startingPopulation: 2.6,
    regions: [{ name: 'Pyongyang' }, { name: 'Nord' }],
    strengths: ['Mines', 'Armée', 'Agriculture'],
    weaknesses: ['Régime isolé', 'Sanctions', 'Économie fermée'],
    bonuses: { researchBonus: 6, militaryBonus: 18, tradeBonus: 0, agricultureBonus: 8 },
  },
  {
    id: 'mongolia',
    name: 'Mongolie',
    flag: '🇲🇳',
    description: 'Mongolie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 25, coal: 20, rareEarths: 15, precious: 10, uranium: 5, ...food(25), water: 20 },
    startingMoney: 3200,
    startingPopulation: 0.3,
    regions: [{ name: 'Oulan-Bator' }, { name: 'Steppe Est' }, { name: 'Désert Gobi' }, { name: 'Nord' }],
    strengths: ['Charbon', 'Cuivre', 'Élevage', 'Terres rares'],
    weaknesses: ['Enclavé', 'Hiver extreme', 'Peu de population'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 10 },
  },
  {
    id: 'bangladesh',
    name: 'Bangladesh',
    flag: '🇧🇩',
    description: 'Bangladesh — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 10, iron: 5, coal: 5, rareEarths: 2, precious: 2, uranium: 0, ...food(70), water: 50 },
    startingMoney: 3200,
    startingPopulation: 17,
    regions: [{ name: 'Dacca' }, { name: 'Delta' }],
    strengths: ['Textile', 'Riz', 'Pêche', 'Main-d\'œuvre'],
    weaknesses: ['Inondations', 'Surpopulation', 'Peu de ressources'],
    bonuses: { researchBonus: 5, militaryBonus: 7, tradeBonus: 12, agricultureBonus: 16 },
  },
  {
    id: 'bhutan',
    name: 'Bhoutan',
    flag: '🇧🇹',
    description: 'Bhoutan — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 3, coal: 1, rareEarths: 2, precious: 3, uranium: 0, ...food(45), water: 80 },
    startingMoney: 4000,
    startingPopulation: 0.08,
    regions: [{ name: 'Thimphou' }, { name: 'Montagnes' }],
    strengths: ['Hydroélectricité', 'Bonheur', 'Tourisme limité'],
    weaknesses: ['Très petit', 'Enclavé', 'Peu de ressources'],
    bonuses: { researchBonus: 8, militaryBonus: 4, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'nepal',
    name: 'Népal',
    flag: '🇳🇵',
    description: 'Népal — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(55), water: 80 },
    startingMoney: 2500,
    startingPopulation: 3,
    regions: [{ name: 'Katmandou' }, { name: 'Himalaya' }],
    strengths: ['Hydroélectricité', 'Tourisme', 'Agriculture'],
    weaknesses: ['Enclavé', 'Pauvreté', 'Infrastructure'],
    bonuses: { researchBonus: 5, militaryBonus: 5, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'afghanistan',
    name: 'Afghanistan',
    flag: '🇦🇫',
    description: 'Afghanistan — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 10, coal: 5, rareEarths: 25, precious: 10, uranium: 0, ...food(45), water: 30 },
    startingMoney: 2000,
    startingPopulation: 4,
    regions: [{ name: 'Kaboul' }, { name: 'Nord' }, { name: 'Sud' }],
    strengths: ['Terres rares', 'Lithium', 'Agriculture'],
    weaknesses: ['Instabilité grave', 'Enclavé', 'Infrastructure nulle'],
    bonuses: { researchBonus: 2, militaryBonus: 10, tradeBonus: 4, agricultureBonus: 10 },
  },
  {
    id: 'tajikistan',
    name: 'Tadjikistan',
    flag: '🇹🇯',
    description: 'Tadjikistan — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 2, iron: 5, coal: 5, rareEarths: 5, precious: 5, uranium: 0, ...food(45), water: 70 },
    startingMoney: 2500,
    startingPopulation: 1,
    regions: [{ name: 'Douchanbe' }, { name: 'Montagnes' }],
    strengths: ['Aluminium', 'Eau', 'Agriculture'],
    weaknesses: ['Enclavé', 'Pauvreté', 'Instabilité'],
    bonuses: { researchBonus: 4, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 12 },
  },
  {
    id: 'kyrgyzstan',
    name: 'Kirghizistan',
    flag: '🇰🇬',
    description: 'Kirghizistan — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 2, iron: 5, coal: 5, rareEarths: 5, precious: 5, uranium: 0, ...food(45), water: 65 },
    startingMoney: 2800,
    startingPopulation: 0.7,
    regions: [{ name: 'Bichkek' }, { name: 'Osh' }],
    strengths: ['Or', 'Eau', 'Tourisme montagne'],
    weaknesses: ['Enclavé', 'Pauvreté', 'Instabilité'],
    bonuses: { researchBonus: 5, militaryBonus: 7, tradeBonus: 8, agricultureBonus: 12 },
  },
  {
    id: 'turkmenistan',
    name: 'Turkménistan',
    flag: '🇹🇲',
    description: 'Turkménistan — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 30, iron: 5, coal: 5, rareEarths: 3, precious: 3, uranium: 2, ...food(25), water: 15 },
    startingMoney: 3800,
    startingPopulation: 0.6,
    regions: [{ name: 'Achgabat' }, { name: 'Mer Caspienne' }, { name: 'Désert' }],
    strengths: ['Gaz naturel', 'Coton', 'Position stratégique'],
    weaknesses: ['Régime autoritaire', 'Eau critique', 'Dépendance gaz'],
    bonuses: { researchBonus: 4, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 8 },
  },
  {
    id: 'syria',
    name: 'Syrie',
    flag: '🇸🇾',
    description: 'Syrie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 30, iron: 5, coal: 5, rareEarths: 3, precious: 5, uranium: 0, ...food(40), water: 25 },
    startingMoney: 2500,
    startingPopulation: 2.1,
    regions: [{ name: 'Damas' }, { name: 'Nord' }],
    strengths: ['Pétrole', 'Agriculture', 'Histoire'],
    weaknesses: ['Guerre', 'Infrastructure détruite', 'Sanctions'],
    bonuses: { researchBonus: 4, militaryBonus: 10, tradeBonus: 6, agricultureBonus: 10 },
  },
  {
    id: 'armenia',
    name: 'Arménie',
    flag: '🇦🇲',
    description: 'Arménie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 10, coal: 5, rareEarths: 5, precious: 5, uranium: 0, ...food(45), water: 35 },
    startingMoney: 3200,
    startingPopulation: 0.3,
    regions: [{ name: 'Erevan' }, { name: 'Province' }],
    strengths: ['Mines', 'Brandy', 'Diaspora tech'],
    weaknesses: ['Enclavé', 'Peu de pétrole', 'Instabilité'],
    bonuses: { researchBonus: 9, militaryBonus: 8, tradeBonus: 10, agricultureBonus: 12 },
  },
  {
    id: 'belarus',
    name: 'Biélorussie',
    flag: '🇧🇾',
    description: 'Biélorussie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 5, rareEarths: 3, precious: 3, uranium: 0, ...food(60), water: 55 },
    startingMoney: 3500,
    startingPopulation: 0.9,
    regions: [{ name: 'Minsk' }, { name: 'Ouest' }, { name: 'Est' }],
    strengths: ['Potasse', 'Industrie soviétique', 'Agriculture'],
    weaknesses: ['Régime autoritaire', 'Sanctions', 'Dépendance Russie'],
    bonuses: { researchBonus: 6, militaryBonus: 10, tradeBonus: 6, agricultureBonus: 12 },
  },
  {
    id: 'austria',
    name: 'Autriche',
    flag: '🇦🇹',
    description: 'Autriche — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 10, coal: 5, rareEarths: 3, precious: 5, uranium: 2, ...food(55), water: 65 },
    startingMoney: 5200,
    startingPopulation: 0.9,
    regions: [{ name: 'Vienne' }, { name: 'Provinces' }],
    strengths: ['Industrie', 'Tourisme', 'Finance'],
    weaknesses: ['Peu d\'énergie fossile', 'Petit', 'Dépendance imports'],
    bonuses: { researchBonus: 12, militaryBonus: 6, tradeBonus: 14, agricultureBonus: 10 },
  },
  {
    id: 'hungary',
    name: 'Hongrie',
    flag: '🇭🇺',
    description: 'Hongrie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 5, rareEarths: 3, precious: 3, uranium: 2, ...food(65), water: 50 },
    startingMoney: 4000,
    startingPopulation: 1,
    regions: [{ name: 'Budapest' }, { name: 'Campagne' }],
    strengths: ['Agriculture', 'Industrie', 'Énergie nucléaire'],
    weaknesses: ['Peu d\'énergie', 'Géopolitique', 'Inflation'],
    bonuses: { researchBonus: 9, militaryBonus: 7, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'moldova',
    name: 'Moldavie',
    flag: '🇲🇩',
    description: 'Moldavie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 2, iron: 3, coal: 3, rareEarths: 2, precious: 2, uranium: 0, ...food(65), water: 45 },
    startingMoney: 2800,
    startingPopulation: 0.3,
    regions: [{ name: 'Chișinău' }, { name: 'Transnistrie' }],
    strengths: ['Agriculture', 'Vin', 'Services'],
    weaknesses: ['Pauvreté', 'Dépendance', 'Politique instable'],
    bonuses: { researchBonus: 6, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 16 },
  },
  {
    id: 'romania',
    name: 'Roumanie',
    flag: '🇷🇴',
    description: 'Roumanie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 20, iron: 15, coal: 12, rareEarths: 5, precious: 5, uranium: 2, ...food(65), water: 50 },
    startingMoney: 3600,
    startingPopulation: 1.9,
    regions: [{ name: 'Bucarest' }, { name: 'Transylvanie' }, { name: 'Moldavie' }],
    strengths: ['Pétrole', 'Agriculture', 'Industrie'],
    weaknesses: ['Corruption', 'Émigration', 'Infrastructure'],
    bonuses: { researchBonus: 8, militaryBonus: 8, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'lithuania',
    name: 'Lituanie',
    flag: '🇱🇹',
    description: 'Lituanie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 2, iron: 5, coal: 3, rareEarths: 2, precious: 2, uranium: 0, ...food(50), water: 50 },
    startingMoney: 4500,
    startingPopulation: 0.3,
    regions: [{ name: 'Vilnius' }, { name: 'Kaunas' }],
    strengths: ['Agriculture', 'Ambre', 'Commerce Baltique'],
    weaknesses: ['Petit', 'Peu de ressources', 'Dépendance énergétique'],
    bonuses: { researchBonus: 9, militaryBonus: 6, tradeBonus: 12, agricultureBonus: 12 },
  },
  {
    id: 'latvia',
    name: 'Lettonie',
    flag: '🇱🇻',
    description: 'Lettonie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 2, iron: 5, coal: 2, rareEarths: 2, precious: 2, uranium: 0, ...food(45), water: 55 },
    startingMoney: 4300,
    startingPopulation: 0.2,
    regions: [{ name: 'Riga' }, { name: 'Latgale' }],
    strengths: ['Bois', 'Commerce maritime', 'Agri'],
    weaknesses: ['Émigration', 'Peu de ressources', 'Petit'],
    bonuses: { researchBonus: 8, militaryBonus: 6, tradeBonus: 12, agricultureBonus: 12 },
  },
  {
    id: 'estonia',
    name: 'Estonie',
    flag: '🇪🇪',
    description: 'Estonie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 5, rareEarths: 2, precious: 2, uranium: 0, ...food(45), water: 55 },
    startingMoney: 5000,
    startingPopulation: 0.15,
    regions: [{ name: 'Tallinn' }, { name: 'Tartu' }],
    strengths: ['Numérique', 'Schiste bitumineux', 'Bois'],
    weaknesses: ['Très petit', 'Peu de ressources', 'Démographie'],
    bonuses: { researchBonus: 14, militaryBonus: 5, tradeBonus: 12, agricultureBonus: 10 },
  },
  {
    id: 'bulgaria',
    name: 'Bulgarie',
    flag: '🇧🇬',
    description: 'Bulgarie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 8, coal: 10, rareEarths: 3, precious: 5, uranium: 2, ...food(60), water: 50 },
    startingMoney: 3500,
    startingPopulation: 0.7,
    regions: [{ name: 'Sofia' }, { name: 'Côte' }],
    strengths: ['Agriculture', 'Tourisme', 'Mines'],
    weaknesses: ['Émigration', 'Corruption', 'Infrastructure'],
    bonuses: { researchBonus: 7, militaryBonus: 6, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'albania',
    name: 'Albanie',
    flag: '🇦🇱',
    description: 'Albanie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 10, coal: 5, rareEarths: 5, precious: 5, uranium: 0, ...food(55), water: 50 },
    startingMoney: 3200,
    startingPopulation: 0.3,
    regions: [{ name: 'Tirana' }, { name: 'Sud' }],
    strengths: ['Chrome', 'Agriculture', 'Tourisme émergent'],
    weaknesses: ['Infrastructure', 'Corruption', 'Émigration'],
    bonuses: { researchBonus: 5, militaryBonus: 7, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'croatia',
    name: 'Croatie',
    flag: '🇭🇷',
    description: 'Croatie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 10, iron: 5, coal: 3, rareEarths: 2, precious: 3, uranium: 0, ...food(55), water: 50 },
    startingMoney: 4200,
    startingPopulation: 0.4,
    regions: [{ name: 'Zagreb' }, { name: 'Côte dalmate' }],
    strengths: ['Tourisme', 'Agriculture', 'Commerce'],
    weaknesses: ['Petit', 'Peu de ressources', 'Post-conflit'],
    bonuses: { researchBonus: 8, militaryBonus: 6, tradeBonus: 14, agricultureBonus: 12 },
  },
  {
    id: 'switzerland',
    name: 'Suisse',
    flag: '🇨🇭',
    description: 'Suisse — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 2, precious: 5, uranium: 0, ...food(40), water: 60 },
    startingMoney: 6500,
    startingPopulation: 0.9,
    regions: [{ name: 'Zurich' }, { name: 'Genève' }],
    strengths: ['Finance', 'Pharma', 'Industrie de précision'],
    weaknesses: ['Pas de pétrole', 'Importation massive', 'Petit'],
    bonuses: { researchBonus: 16, militaryBonus: 4, tradeBonus: 18, agricultureBonus: 6 },
  },
  {
    id: 'luxembourg',
    name: 'Luxembourg',
    flag: '🇱🇺',
    description: 'Luxembourg — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 2, precious: 2, uranium: 0, ...food(40), water: 50 },
    startingMoney: 7000,
    startingPopulation: 0.07,
    regions: [{ name: 'Luxembourg Ville' }, { name: 'Campagne' }],
    strengths: ['Finance', 'Fonds', 'Acier historique'],
    weaknesses: ['Très petit', 'Peu de ressources', 'Dépendant EU'],
    bonuses: { researchBonus: 10, militaryBonus: 3, tradeBonus: 22, agricultureBonus: 6 },
  },
  {
    id: 'belgium',
    name: 'Belgique',
    flag: '🇧🇪',
    description: 'Belgique — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 5, rareEarths: 3, precious: 3, uranium: 2, ...food(50), water: 50 },
    startingMoney: 5300,
    startingPopulation: 1.2,
    regions: [{ name: 'Bruxelles' }, { name: 'Flandre' }],
    strengths: ['Finance', 'Chimie', 'Hub européen'],
    weaknesses: ['Peu de ressources', 'Dépendance', 'Politique fragile'],
    bonuses: { researchBonus: 12, militaryBonus: 5, tradeBonus: 16, agricultureBonus: 8 },
  },
  {
    id: 'portugal',
    name: 'Portugal',
    flag: '🇵🇹',
    description: 'Portugal — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 3, rareEarths: 3, precious: 5, uranium: 0, ...food(60), water: 45 },
    startingMoney: 4200,
    startingPopulation: 1,
    regions: [{ name: 'Lisbonne' }, { name: 'Porto' }],
    strengths: ['Agriculture', 'Pêche', 'Tourisme'],
    weaknesses: ['Peu de pétrole', 'Dépendance', 'Industrie légère'],
    bonuses: { researchBonus: 8, militaryBonus: 5, tradeBonus: 14, agricultureBonus: 14 },
  },
  {
    id: 'ireland',
    name: 'Irlande',
    flag: '🇮🇪',
    description: 'Irlande — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 10, iron: 5, coal: 2, rareEarths: 2, precious: 3, uranium: 0, ...food(50), water: 70 },
    startingMoney: 5800,
    startingPopulation: 0.5,
    regions: [{ name: 'Dublin' }, { name: 'Ouest' }],
    strengths: ['Tech hub', 'Pharma', 'Agriculture verte'],
    weaknesses: ['Pas d\'énergie fossile', 'Petit', 'Dépendance UK/EU'],
    bonuses: { researchBonus: 15, militaryBonus: 4, tradeBonus: 16, agricultureBonus: 10 },
  },
  {
    id: 'new_caledonia',
    name: 'Nouvelle-Calédonie',
    flag: '🇳🇨',
    description: 'Nouvelle-Calédonie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 15, precious: 10, uranium: 0, ...food(35), water: 55 },
    startingMoney: 5500,
    startingPopulation: 0.03,
    regions: [{ name: 'Nouméa' }, { name: 'Nord' }],
    strengths: ['Nickel mondial', 'Tourisme', 'Stabilité française'],
    weaknesses: ['Dépendance France', 'Petit', 'Population faible'],
    bonuses: { researchBonus: 8, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 8 },
  },
  {
    id: 'solomon_is',
    name: 'Îles Salomon',
    flag: '🇸🇧',
    description: 'Îles Salomon — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 2, precious: 3, uranium: 0, ...food(55), water: 70 },
    startingMoney: 2500,
    startingPopulation: 0.07,
    regions: [{ name: 'Honiara' }, { name: 'Guadalcanal' }],
    strengths: ['Bois', 'Pêche', 'Ressources marines'],
    weaknesses: ['Isolé', 'Infrastructure', 'Peu de ressources'],
    bonuses: { researchBonus: 4, militaryBonus: 4, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'new_zealand',
    name: 'Nouvelle-Zélande',
    flag: '🇳🇿',
    description: 'Nouvelle-Zélande — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 10, coal: 5, rareEarths: 5, precious: 10, uranium: 0, ...food(65), water: 70 },
    startingMoney: 5500,
    startingPopulation: 0.5,
    regions: [{ name: 'Auckland' }, { name: 'Wellington' }, { name: 'Sud' }],
    strengths: ['Agriculture', 'Laine', 'Pêche', 'Tourisme'],
    weaknesses: ['Population faible', 'Isolé', 'Peu de minerais'],
    bonuses: { researchBonus: 12, militaryBonus: 4, tradeBonus: 14, agricultureBonus: 16 },
  },
  {
    id: 'sri_lanka',
    name: 'Sri Lanka',
    flag: '🇱🇰',
    description: 'Sri Lanka — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 5, precious: 5, uranium: 0, ...food(65), water: 60 },
    startingMoney: 3500,
    startingPopulation: 2.2,
    regions: [{ name: 'Colombo' }, { name: 'Kandy' }],
    strengths: ['Thé', 'Tourisme', 'Épices', 'Pêche'],
    weaknesses: ['Peu de pétrole', 'Dette', 'Infrastructure'],
    bonuses: { researchBonus: 7, militaryBonus: 5, tradeBonus: 12, agricultureBonus: 16 },
  },
  {
    id: 'taiwan',
    name: 'Taïwan',
    flag: '🇹🇼',
    description: 'Taïwan — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 5, rareEarths: 5, precious: 5, uranium: 2, ...food(40), water: 40 },
    startingMoney: 5500,
    startingPopulation: 2.4,
    regions: [{ name: 'Taipei' }, { name: 'Sud' }],
    strengths: ['Semi-conducteurs', 'Électronique', 'Commerce'],
    weaknesses: ['Revendication Chine', 'Peu de ressources', 'Petit'],
    bonuses: { researchBonus: 20, militaryBonus: 8, tradeBonus: 16, agricultureBonus: 4 },
  },
  {
    id: 'denmark',
    name: 'Danemark',
    flag: '🇩🇰',
    description: 'Danemark — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 20, iron: 5, coal: 5, rareEarths: 2, precious: 5, uranium: 2, ...food(45), water: 60 },
    startingMoney: 5800,
    startingPopulation: 0.6,
    regions: [{ name: 'Copenhague' }, { name: 'Jutland' }],
    strengths: ['Agriculture', 'Éolien', 'Pêche', 'Commerce'],
    weaknesses: ['Petit', 'Peu de minerais', 'Coûts élevés'],
    bonuses: { researchBonus: 14, militaryBonus: 6, tradeBonus: 14, agricultureBonus: 12 },
  },
  {
    id: 'iceland',
    name: 'Islande',
    flag: '🇮🇸',
    description: 'Islande — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 0, rareEarths: 2, precious: 3, uranium: 0, ...food(20), water: 90 },
    startingMoney: 5800,
    startingPopulation: 0.04,
    regions: [{ name: 'Reykjavik' }, { name: 'Intérieur' }],
    strengths: ['Géothermie', 'Pêche', 'Eau', 'Aluminium'],
    weaknesses: ['Population infime', 'Petit', 'Dépendance imports'],
    bonuses: { researchBonus: 13, militaryBonus: 4, tradeBonus: 14, agricultureBonus: 6 },
  },
  {
    id: 'azerbaijan',
    name: 'Azerbaïdjan',
    flag: '🇦🇿',
    description: 'Azerbaïdjan — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 60, iron: 10, coal: 5, rareEarths: 5, precious: 5, uranium: 0, ...food(40), water: 30 },
    startingMoney: 4500,
    startingPopulation: 1,
    regions: [{ name: 'Bakou' }, { name: 'Karabakh' }],
    strengths: ['Pétrole', 'Gaz', 'Position stratégique'],
    weaknesses: ['Corruption', 'Post-pétrole', 'Instabilité'],
    bonuses: { researchBonus: 7, militaryBonus: 10, tradeBonus: 12, agricultureBonus: 8 },
  },
  {
    id: 'georgia',
    name: 'Géorgie',
    flag: '🇬🇪',
    description: 'Géorgie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 5, coal: 5, rareEarths: 3, precious: 5, uranium: 0, ...food(55), water: 55 },
    startingMoney: 3500,
    startingPopulation: 0.4,
    regions: [{ name: 'Tbilissi' }, { name: 'Ouest' }],
    strengths: ['Vin', 'Tourisme', 'Mines', 'Agriculture'],
    weaknesses: ['Instabilité régionale', 'Peu d\'énergie', 'Corruption'],
    bonuses: { researchBonus: 8, militaryBonus: 7, tradeBonus: 12, agricultureBonus: 14 },
  },
  {
    id: 'philippines',
    name: 'Philippines',
    flag: '🇵🇭',
    description: 'Philippines — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 10, iron: 15, coal: 5, rareEarths: 10, precious: 10, uranium: 0, ...food(70), water: 65 },
    startingMoney: 3500,
    startingPopulation: 11,
    regions: [{ name: 'Manille' }, { name: 'Visayas' }, { name: 'Mindanao' }],
    strengths: ['BPO', 'Agriculture', 'Ressources marines'],
    weaknesses: ['Typhons', 'Infrastructure insulaire', 'Corruption'],
    bonuses: { researchBonus: 7, militaryBonus: 7, tradeBonus: 12, agricultureBonus: 14 },
  },
  {
    id: 'malaysia',
    name: 'Malaisie',
    flag: '🇲🇾',
    description: 'Malaisie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 50, iron: 10, coal: 5, rareEarths: 10, precious: 10, uranium: 0, ...food(65), water: 65 },
    startingMoney: 4500,
    startingPopulation: 3.3,
    regions: [{ name: 'Kuala Lumpur' }, { name: 'Sabah' }, { name: 'Sarawak' }],
    strengths: ['Pétrole', 'Palme', 'Électronique'],
    weaknesses: ['Dépendance pétrole', 'Inégalités', 'Eau Sarawak'],
    bonuses: { researchBonus: 9, militaryBonus: 7, tradeBonus: 13, agricultureBonus: 12 },
  },
  {
    id: 'brunei',
    name: 'Brunéi',
    flag: '🇧🇳',
    description: 'Brunéi — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 60, iron: 3, coal: 2, rareEarths: 2, precious: 3, uranium: 0, ...food(20), water: 30 },
    startingMoney: 7000,
    startingPopulation: 0.05,
    regions: [{ name: 'Bandar Seri Begawan' }, { name: 'Intérieur' }],
    strengths: ['Pétrole', 'Gaz', 'Fonds souverain'],
    weaknesses: ['Très petit', 'Post-pétrole', 'Dépendance'],
    bonuses: { researchBonus: 5, militaryBonus: 6, tradeBonus: 14, agricultureBonus: 4 },
  },
  {
    id: 'slovenia',
    name: 'Slovénie',
    flag: '🇸🇮',
    description: 'Slovénie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 2, iron: 5, coal: 3, rareEarths: 3, precious: 3, uranium: 0, ...food(45), water: 65 },
    startingMoney: 5000,
    startingPopulation: 0.2,
    regions: [{ name: 'Ljubljana' }, { name: 'Alpes' }],
    strengths: ['Industrie', 'Tourisme', 'Eau'],
    weaknesses: ['Très petit', 'Peu de pétrole', 'Dépendance'],
    bonuses: { researchBonus: 10, militaryBonus: 5, tradeBonus: 12, agricultureBonus: 10 },
  },
  {
    id: 'finland',
    name: 'Finlande',
    flag: '🇫🇮',
    description: 'Finlande — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 15, coal: 5, rareEarths: 3, precious: 5, uranium: 2, ...food(35), water: 80 },
    startingMoney: 5500,
    startingPopulation: 0.6,
    regions: [{ name: 'Helsinki' }, { name: 'Laponie' }, { name: 'Lakeland' }],
    strengths: ['Bois', 'High-tech Nokia', 'Eau', 'Mines'],
    weaknesses: ['Population faible', 'Hiver long', 'Peu de pétrole'],
    bonuses: { researchBonus: 15, militaryBonus: 6, tradeBonus: 12, agricultureBonus: 8 },
  },
  {
    id: 'slovakia',
    name: 'Slovaquie',
    flag: '🇸🇰',
    description: 'Slovaquie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 2, iron: 8, coal: 8, rareEarths: 3, precious: 3, uranium: 2, ...food(55), water: 55 },
    startingMoney: 4200,
    startingPopulation: 0.5,
    regions: [{ name: 'Bratislava' }, { name: 'Est' }],
    strengths: ['Automobile', 'Industrie', 'Agriculture'],
    weaknesses: ['Petit', 'Peu de ressources', 'Dépendance imports'],
    bonuses: { researchBonus: 9, militaryBonus: 7, tradeBonus: 12, agricultureBonus: 12 },
  },
  {
    id: 'czechia',
    name: 'Tchéquie',
    flag: '🇨🇿',
    description: 'Tchéquie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 3, iron: 10, coal: 15, rareEarths: 3, precious: 5, uranium: 2, ...food(55), water: 55 },
    startingMoney: 4800,
    startingPopulation: 1.1,
    regions: [{ name: 'Prague' }, { name: 'Moravie' }],
    strengths: ['Industrie', 'Automobile', 'Bière'],
    weaknesses: ['Peu d\'énergie propre', 'Charbon', 'Petit'],
    bonuses: { researchBonus: 11, militaryBonus: 8, tradeBonus: 12, agricultureBonus: 10 },
  },
  {
    id: 'eritrea',
    name: 'Érythrée',
    flag: '🇪🇷',
    description: 'Érythrée — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 15, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(25), water: 20 },
    startingMoney: 2500,
    startingPopulation: 0.4,
    regions: [{ name: 'Asmara' }, { name: 'Côte' }],
    strengths: ['Mines', 'Pêche', 'Côte stratégique'],
    weaknesses: ['Isolement', 'Régime autoritaire', 'Infrastructure'],
    bonuses: { researchBonus: 3, militaryBonus: 12, tradeBonus: 6, agricultureBonus: 8 },
  },
  {
    id: 'paraguay',
    name: 'Paraguay',
    flag: '🇵🇾',
    description: 'Paraguay — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 3, uranium: 0, ...food(65), water: 70 },
    startingMoney: 3200,
    startingPopulation: 0.7,
    regions: [{ name: 'Asunción' }, { name: 'Est' }, { name: 'Chaco' }],
    strengths: ['Soja', 'Bœuf', 'Hydroélectricité', 'Coton'],
    weaknesses: ['Enclavé', 'Peu de ressources', 'Corruption'],
    bonuses: { researchBonus: 5, militaryBonus: 5, tradeBonus: 10, agricultureBonus: 16 },
  },
  {
    id: 'yemen',
    name: 'Yémen',
    flag: '🇾🇪',
    description: 'Yémen — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 25, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(35), water: 15 },
    startingMoney: 2000,
    startingPopulation: 3.3,
    regions: [{ name: 'Sanaa' }, { name: 'Aden' }, { name: 'Est' }],
    strengths: ['Pétrole', 'Pêche', 'Agriculture'],
    weaknesses: ['Guerre', 'Infrastructure détruite', 'Eau critique'],
    bonuses: { researchBonus: 3, militaryBonus: 10, tradeBonus: 6, agricultureBonus: 8 },
  },
  {
    id: 'n_cyprus',
    name: 'Chypre du Nord',
    flag: '🇨🇾',
    description: 'Chypre du Nord — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 3, coal: 1, rareEarths: 2, precious: 3, uranium: 0, ...food(40), water: 30 },
    startingMoney: 3500,
    startingPopulation: 0.4,
    regions: [{ name: 'Nicosie Nord' }, { name: 'Famagouste' }],
    strengths: ['Agriculture', 'Tourisme', 'Position'],
    weaknesses: ['Non reconnu', 'Peu de ressources', 'Économie limitée'],
    bonuses: { researchBonus: 6, militaryBonus: 5, tradeBonus: 12, agricultureBonus: 12 },
  },
  {
    id: 'cyprus',
    name: 'Chypre',
    flag: '🇨🇾',
    description: 'Chypre — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 3, coal: 2, rareEarths: 2, precious: 5, uranium: 0, ...food(45), water: 30 },
    startingMoney: 4500,
    startingPopulation: 0.9,
    regions: [{ name: 'Nicosie' }, { name: 'Limassol' }],
    strengths: ['Tourisme', 'Services', 'Gaz offshore'],
    weaknesses: ['Division', 'Eau limitée', 'Dépendance imports'],
    bonuses: { researchBonus: 8, militaryBonus: 5, tradeBonus: 16, agricultureBonus: 10 },
  },
  {
    id: 'djibouti',
    name: 'Djibouti',
    flag: '🇩🇯',
    description: 'Djibouti — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 0, coal: 0, rareEarths: 0, precious: 0, uranium: 0, ...food(5), water: 10 },
    startingMoney: 3500,
    startingPopulation: 0.1,
    regions: [{ name: 'Djibouti Ville' }, { name: 'Intérieur' }],
    strengths: ['Position stratégique', 'Port', 'Services'],
    weaknesses: ['Quasi pas de ressources', 'Eau nulle', 'Petit'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 18, agricultureBonus: 2 },
  },
  {
    id: 'somaliland',
    name: 'Somaliland',
    flag: '🇸🇴',
    description: 'Somaliland — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 3, coal: 1, rareEarths: 2, precious: 3, uranium: 0, ...food(20), water: 15 },
    startingMoney: 2500,
    startingPopulation: 0.4,
    regions: [{ name: 'Hargeisa' }, { name: 'Côte' }],
    strengths: ['Stabilité relative', 'Bétail', 'Côte'],
    weaknesses: ['Non reconnu', 'Peu de ressources', 'Isolé'],
    bonuses: { researchBonus: 3, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 8 },
  },
  {
    id: 'uganda',
    name: 'Ouganda',
    flag: '🇺🇬',
    description: 'Ouganda — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 15, iron: 5, coal: 2, rareEarths: 5, precious: 5, uranium: 0, ...food(65), water: 55 },
    startingMoney: 2800,
    startingPopulation: 4.8,
    regions: [{ name: 'Kampala' }, { name: 'Nord' }, { name: 'Lac Victoria' }],
    strengths: ['Agriculture', 'Café', 'Pétrole émergent'],
    weaknesses: ['Infrastructure', 'Instabilité nord', 'Santé'],
    bonuses: { researchBonus: 5, militaryBonus: 7, tradeBonus: 8, agricultureBonus: 16 },
  },
  {
    id: 'rwanda',
    name: 'Rwanda',
    flag: '🇷🇼',
    description: 'Rwanda — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 2, rareEarths: 3, precious: 5, uranium: 0, ...food(55), water: 50 },
    startingMoney: 3200,
    startingPopulation: 1.4,
    regions: [{ name: 'Kigali' }, { name: 'Ouest' }],
    strengths: ['Stabilité', 'Café', 'Tourisme gorilles'],
    weaknesses: ['Enclavé', 'Peu de ressources', 'Trop dense'],
    bonuses: { researchBonus: 8, militaryBonus: 6, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'bosnia_and_herz',
    name: 'Bosnie-Herzégovine',
    flag: '🇧🇦',
    description: 'Bosnie-Herzégovine — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 3, iron: 10, coal: 12, rareEarths: 3, precious: 3, uranium: 0, ...food(55), water: 55 },
    startingMoney: 3000,
    startingPopulation: 0.3,
    regions: [{ name: 'Sarajevo' }, { name: 'Republika Srpska' }],
    strengths: ['Agriculture', 'Bois', 'Industrie lourde'],
    weaknesses: ['Instabilité', 'Post-conflit', 'Infrastructure'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 14 },
  },
  {
    id: 'macedonia',
    name: 'Macédoine du Nord',
    flag: '🇲🇰',
    description: 'Macédoine du Nord — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 2, iron: 8, coal: 5, rareEarths: 3, precious: 3, uranium: 0, ...food(55), water: 45 },
    startingMoney: 3200,
    startingPopulation: 0.2,
    regions: [{ name: 'Skopje' }, { name: 'Lac Ohrid' }],
    strengths: ['Chrome', 'Agriculture', 'Tourisme'],
    weaknesses: ['Enclavement', 'Peu de ressources', 'Emploi faible'],
    bonuses: { researchBonus: 6, militaryBonus: 6, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'serbia',
    name: 'Serbie',
    flag: '🇷🇸',
    description: 'Serbie — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 10, coal: 12, rareEarths: 5, precious: 5, uranium: 0, ...food(60), water: 55 },
    startingMoney: 3800,
    startingPopulation: 0.7,
    regions: [{ name: 'Belgrade' }, { name: 'Vojvodine' }],
    strengths: ['Agriculture', 'Industrie', 'Mines'],
    weaknesses: ['Dépendance énergétique', 'Instabilité', 'Infrastructure'],
    bonuses: { researchBonus: 7, militaryBonus: 8, tradeBonus: 10, agricultureBonus: 14 },
  },
  {
    id: 'montenegro',
    name: 'Monténégro',
    flag: '🇲🇪',
    description: 'Monténégro — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 0, iron: 5, coal: 3, rareEarths: 3, precious: 3, uranium: 0, ...food(45), water: 60 },
    startingMoney: 4000,
    startingPopulation: 0.06,
    regions: [{ name: 'Podgorica' }, { name: 'Côte' }],
    strengths: ['Tourisme', 'Aluminium', 'Agriculture'],
    weaknesses: ['Très petit', 'Peu de ressources', 'Dépendance'],
    bonuses: { researchBonus: 6, militaryBonus: 5, tradeBonus: 12, agricultureBonus: 12 },
  },
  {
    id: 'kosovo',
    name: 'Kosovo',
    flag: '🇽🇰',
    description: 'Kosovo — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 5, iron: 8, coal: 40, rareEarths: 3, precious: 5, uranium: 0, ...food(50), water: 45 },
    startingMoney: 2800,
    startingPopulation: 0.2,
    regions: [{ name: 'Pristina' }, { name: 'Metohija' }],
    strengths: ['Lignite', 'Agriculture', 'Jeunesse'],
    weaknesses: ['Statut disputé', 'Économie fragile', 'Dépendance'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 12 },
  },
  {
    id: 'trinidad_and_tobago',
    name: 'Trinité-et-Tobago',
    flag: '🇹🇹',
    description: 'Trinité-et-Tobago — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 50, iron: 5, coal: 5, rareEarths: 3, precious: 3, uranium: 0, ...food(40), water: 55 },
    startingMoney: 5500,
    startingPopulation: 0.14,
    regions: [{ name: 'Port of Spain' }, { name: 'Tobago' }],
    strengths: ['Pétrole', 'Gaz', 'Industrie pétro-chimique'],
    weaknesses: ['Post-pétrole', 'Petit', 'Dépendance'],
    bonuses: { researchBonus: 7, militaryBonus: 6, tradeBonus: 14, agricultureBonus: 8 },
  },
  {
    id: 's_sudan',
    name: 'Soudan du Sud',
    flag: '🇸🇸',
    description: 'Soudan du Sud — nation jouable dans Empire du Commerce.',
    startingResources: { oil: 45, iron: 5, coal: 3, rareEarths: 3, precious: 5, uranium: 0, ...food(35), water: 40 },
    startingMoney: 2500,
    startingPopulation: 1.2,
    regions: [{ name: 'Juba' }, { name: 'Nord' }, { name: 'Sud' }],
    strengths: ['Pétrole', 'Eau du Nil', 'Bétail'],
    weaknesses: ['Guerre civile', 'Infrastructure nulle', 'Enclavement'],
    bonuses: { researchBonus: 3, militaryBonus: 10, tradeBonus: 6, agricultureBonus: 12 },
  },
