services:
  - type: web
    name: undercover-server
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build --workspace=packages/shared && npm run build --workspace=packages/uno-shared && npm run build --workspace=apps/server
    startCommand: npx tsx apps/server/src/index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
