import type { WordPair } from '@undercover/shared';

/**
 * Word database for Undercover game
 * 175 French word pairs across 5 categories (35 per category)
 */
export type RealWordCategory = 'facile' | 'expert' | 'adulte' | 'gastronomie' | 'voyage';

export const wordDatabase: Record<RealWordCategory, WordPair[]> = {
  facile: [
    { civil: 'Chat', undercover: 'Chien' },
    { civil: 'Pizza', undercover: 'Hamburger' },
    { civil: 'Café', undercover: 'Thé' },
    { civil: 'Vélo', undercover: 'Moto' },
    { civil: 'Livre', undercover: 'Magazine' },
    { civil: 'Pomme', undercover: 'Poire' },
    { civil: 'Soleil', undercover: 'Lune' },
    { civil: 'Mer', undercover: 'Océan' },
    { civil: 'Montagne', undercover: 'Colline' },
    { civil: 'Été', undercover: 'Printemps' },
    { civil: 'Voiture', undercover: 'Camion' },
    { civil: 'Chaussures', undercover: 'Baskets' },
    { civil: 'Guitare', undercover: 'Piano' },
    { civil: 'Crayon', undercover: 'Stylo' },
    { civil: 'Chapeau', undercover: 'Casquette' },
    { civil: 'Fenêtre', undercover: 'Porte' },
    { civil: 'Cuillère', undercover: 'Fourchette' },
    { civil: 'Coussin', undercover: 'Oreiller' },
    { civil: 'Rivière', undercover: 'Lac' },
    { civil: 'Bus', undercover: 'Tramway' },
    { civil: 'Bougie', undercover: 'Lampe' },
    { civil: 'Chaise', undercover: 'Tabouret' },
    { civil: 'Savon', undercover: 'Shampoing' },
    { civil: 'Glace', undercover: 'Sorbet' },
    { civil: 'Pluie', undercover: 'Neige' },
    { civil: 'Écharpe', undercover: 'Bonnet' },
    { civil: 'Souris', undercover: 'Hamster' },
    { civil: 'Bain', undercover: 'Douche' },
    { civil: 'Canapé', undercover: 'Fauteuil' },
    { civil: 'Miroir', undercover: 'Vitre' },
    { civil: 'Horloge', undercover: 'Montre' },
    { civil: 'Parapluie', undercover: 'Imperméable' },
    { civil: 'Escalier', undercover: 'Ascenseur' },
    { civil: 'Jardin', undercover: 'Parc' },
    { civil: 'Ballon', undercover: 'Balle' },
  ],

  expert: [
    { civil: 'Démocratie', undercover: 'République' },
    { civil: 'Yoga', undercover: 'Pilates' },
    { civil: 'Philosophie', undercover: 'Psychologie' },
    { civil: 'Jazz', undercover: 'Blues' },
    { civil: 'Roman', undercover: 'Nouvelle' },
    { civil: 'Sculpture', undercover: 'Peinture' },
    { civil: 'Stratégie', undercover: 'Tactique' },
    { civil: 'Théorie', undercover: 'Pratique' },
    { civil: 'Éthique', undercover: 'Morale' },
    { civil: 'Science', undercover: 'Technologie' },
    { civil: 'Architecture', undercover: 'Ingénierie' },
    { civil: 'Économie', undercover: 'Finance' },
    { civil: 'Météore', undercover: 'Comète' },
    { civil: 'Opéra', undercover: 'Ballet' },
    { civil: 'Athéisme', undercover: 'Agnosticisme' },
    { civil: 'Métaphore', undercover: 'Comparaison' },
    { civil: 'Socialisme', undercover: 'Communisme' },
    { civil: 'Nostalgie', undercover: 'Mélancolie' },
    { civil: 'Diplomatie', undercover: 'Négociation' },
    { civil: 'Renaissance', undercover: 'Baroque' },
    { civil: 'Tragédie', undercover: 'Comédie' },
    { civil: 'Intuition', undercover: 'Instinct' },
    { civil: 'Utopie', undercover: 'Dystopie' },
    { civil: 'Empathie', undercover: 'Sympathie' },
    { civil: 'Anarchie', undercover: 'Chaos' },
    { civil: 'Mythologie', undercover: 'Légende' },
    { civil: 'Calligraphie', undercover: 'Typographie' },
    { civil: 'Astronomie', undercover: 'Astrologie' },
    { civil: 'Karma', undercover: 'Destin' },
    { civil: 'Paradoxe', undercover: 'Dilemme' },
    { civil: 'Censure', undercover: 'Propagande' },
    { civil: 'Hérésie', undercover: 'Blasphème' },
    { civil: 'Révolution', undercover: 'Réforme' },
    { civil: 'Poésie', undercover: 'Prose' },
    { civil: 'Ironie', undercover: 'Sarcasme' },
  ],

  adulte: [
    { civil: 'Tinder', undercover: 'Bumble' },
    { civil: 'Gueule de bois', undercover: 'Indigestion' },
    { civil: 'Netflix', undercover: 'Amazon Prime' },
    { civil: 'Instagram', undercover: 'TikTok' },
    { civil: 'Ex', undercover: 'Crush' },
    { civil: 'Ghosting', undercover: 'Friendzone' },
    { civil: 'Burnout', undercover: 'Dépression' },
    { civil: 'Stalker', undercover: 'Fan' },
    { civil: 'Influenceur', undercover: 'Youtubeur' },
    { civil: 'Spam', undercover: 'Pub' },
    { civil: 'Swiper', undercover: 'Liker' },
    { civil: 'Story', undercover: 'Post' },
    { civil: 'Brunch', undercover: 'Apéro' },
    { civil: 'Coloc', undercover: 'Voisin' },
    { civil: 'Uber', undercover: 'Taxi' },
    { civil: 'Podcast', undercover: 'Radio' },
    { civil: 'Freelance', undercover: 'Intérimaire' },
    { civil: 'Startup', undercover: 'PME' },
    { civil: 'Hangover', undercover: 'Jet lag' },
    { civil: 'Red flag', undercover: 'Green flag' },
    { civil: 'Situationship', undercover: 'Relation libre' },
    { civil: 'Meme', undercover: 'Gif' },
    { civil: 'Coworking', undercover: 'Télétravail' },
    { civil: 'Reel', undercover: 'Short' },
    { civil: 'Spotify', undercover: 'Deezer' },
    { civil: 'Foodporn', undercover: 'Mukbang' },
    { civil: 'Binge watching', undercover: 'Zapping' },
    { civil: 'Dark humor', undercover: 'Second degré' },
    { civil: 'Cancel culture', undercover: 'Boycott' },
    { civil: 'FOMO', undercover: 'YOLO' },
    { civil: 'Detox digitale', undercover: 'Mode avion' },
    { civil: 'Hater', undercover: 'Troll' },
    { civil: 'Flexer', undercover: 'Frimer' },
    { civil: 'DM', undercover: 'Texto' },
    { civil: 'Afterwork', undercover: 'Happy hour' },
  ],

  gastronomie: [
    { civil: 'Croissant', undercover: 'Pain au chocolat' },
    { civil: 'Champagne', undercover: 'Prosecco' },
    { civil: 'Café', undercover: 'Espresso' },
    { civil: 'Vin rouge', undercover: 'Vin blanc' },
    { civil: 'Fromage', undercover: 'Yaourt' },
    { civil: 'Chocolat', undercover: 'Nutella' },
    { civil: 'Burger', undercover: 'Sandwich' },
    { civil: 'Sushi', undercover: 'Sashimi' },
    { civil: 'Bière', undercover: 'Cidre' },
    { civil: 'Gâteau', undercover: 'Tarte' },
    { civil: 'Steak', undercover: 'Côtelette' },
    { civil: 'Baguette', undercover: 'Pain de mie' },
    { civil: 'Raclette', undercover: 'Fondue' },
    { civil: 'Crêpe', undercover: 'Gaufre' },
    { civil: 'Tiramisu', undercover: 'Panna cotta' },
    { civil: 'Mojito', undercover: 'Caïpirinha' },
    { civil: 'Ramen', undercover: 'Pho' },
    { civil: 'Tacos', undercover: 'Burrito' },
    { civil: 'Macaron', undercover: 'Meringue' },
    { civil: 'Risotto', undercover: 'Paella' },
    { civil: 'Brioche', undercover: 'Pain au lait' },
    { civil: 'Mozzarella', undercover: 'Burrata' },
    { civil: 'Wasabi', undercover: 'Moutarde' },
    { civil: 'Couscous', undercover: 'Tajine' },
    { civil: 'Cappuccino', undercover: 'Latte' },
    { civil: 'Guacamole', undercover: 'Houmous' },
    { civil: 'Brownie', undercover: 'Cookie' },
    { civil: 'Salade César', undercover: 'Salade niçoise' },
    { civil: 'Kebab', undercover: 'Shawarma' },
    { civil: 'Pesto', undercover: 'Tapenade' },
    { civil: 'Sorbet citron', undercover: 'Granité' },
    { civil: 'Dim sum', undercover: 'Gyoza' },
    { civil: 'Cheddar', undercover: 'Gruyère' },
    { civil: 'Croûton', undercover: 'Bruschetta' },
    { civil: 'Churros', undercover: 'Beignet' },
  ],

  voyage: [
    { civil: 'Avion', undercover: 'Hélicoptère' },
    { civil: 'Paris', undercover: 'Londres' },
    { civil: 'Hôtel', undercover: 'Auberge' },
    { civil: 'Valise', undercover: 'Sac à dos' },
    { civil: 'Plage', undercover: 'Piscine' },
    { civil: 'Train', undercover: 'Métro' },
    { civil: 'Passeport', undercover: 'Visa' },
    { civil: 'Croisière', undercover: 'Ferry' },
    { civil: 'Touriste', undercover: 'Voyageur' },
    { civil: 'Montagne', undercover: 'Campagne' },
    { civil: 'Camping', undercover: 'Randonnée' },
    { civil: 'Réservation', undercover: 'Billet' },
    { civil: 'Safari', undercover: 'Zoo' },
    { civil: 'Carte postale', undercover: 'Souvenir' },
    { civil: 'Auberge de jeunesse', undercover: 'Airbnb' },
    { civil: 'Aéroport', undercover: 'Gare' },
    { civil: 'Excursion', undercover: 'Visite guidée' },
    { civil: 'Hamac', undercover: 'Transat' },
    { civil: 'Île', undercover: 'Presqu\'île' },
    { civil: 'Sac de couchage', undercover: 'Tente' },
    { civil: 'Road trip', undercover: 'Tour du monde' },
    { civil: 'Douane', undercover: 'Contrôle de sécurité' },
    { civil: 'Guide touristique', undercover: 'GPS' },
    { civil: 'Jet privé', undercover: 'Première classe' },
    { civil: 'Bronzer', undercover: 'Coup de soleil' },
    { civil: 'Décalage horaire', undercover: 'Mal des transports' },
    { civil: 'Carte d\'embarquement', undercover: 'Étiquette bagage' },
    { civil: 'Refuge', undercover: 'Bivouac' },
    { civil: 'Spa', undercover: 'Hammam' },
    { civil: 'New York', undercover: 'Los Angeles' },
    { civil: 'Tokyo', undercover: 'Séoul' },
    { civil: 'Crème solaire', undercover: 'Lunettes de soleil' },
    { civil: 'Convertisseur', undercover: 'Adaptateur' },
    { civil: 'Duty free', undercover: 'Boutique souvenir' },
    { civil: 'Escale', undercover: 'Correspondance' },
  ],
};
