/**
 * Empire du Commerce — Country Profiles
 * 12 asymmetric country profiles for 4-12 player games
 */

import type { CountryProfile } from '@undercover/shared';

export const COUNTRY_PROFILES: CountryProfile[] = [
  {
    id: 'japan',
    name: 'Japon',
    flag: '🇯🇵',
    description: 'Nation insulaire technologique, pauvre en ressources mais riche en innovation.',
    startingResources: { oil: 10, minerals: 20, agriculture: 40, water: 50 },
    startingMoney: 5500,
    startingPopulation: 12.5,
    regions: [
      { name: 'Kanto' }, { name: 'Kansai' }, { name: 'Hokkaido' },
      { name: 'Kyushu' }, { name: 'Tohoku' },
    ],
    strengths: ['Recherche avancée', 'Électronique', 'Outils robotisés'],
    weaknesses: ['Peu de pétrole', 'Peu de minerais', 'Dépendant des imports'],
    bonuses: { researchBonus: 18, militaryBonus: 5, tradeBonus: 12, agricultureBonus: 5 },
  },
  {
    id: 'brazil',
    name: 'Brésil',
    flag: '🇧🇷',
    description: 'Géant tropical riche en ressources naturelles et en agriculture.',
    startingResources: { oil: 50, minerals: 60, agriculture: 90, water: 80 },
    startingMoney: 4500,
    startingPopulation: 21.0,
    regions: [
      { name: 'São Paulo' }, { name: 'Amazonie' }, { name: 'Rio' },
      { name: 'Minas Gerais' }, { name: 'Bahia' }, { name: 'Paraná' },
    ],
    strengths: ['Agriculture massive', 'Eau abondante', 'Population nombreuse'],
    weaknesses: ['Recherche faible', 'Industrie basique', 'Corruption'],
    bonuses: { researchBonus: 5, militaryBonus: 8, tradeBonus: 10, agricultureBonus: 17 },
  },
  {
    id: 'germany',
    name: 'Allemagne',
    flag: '🇩🇪',
    description: 'Puissance industrielle au cœur de l\'Europe, maîtresse de la manufacture.',
    startingResources: { oil: 15, minerals: 40, agriculture: 55, water: 60 },
    startingMoney: 5800,
    startingPopulation: 8.3,
    regions: [
      { name: 'Bavière' }, { name: 'Rhénanie' }, { name: 'Saxe' },
      { name: 'Basse-Saxe' }, { name: 'Hesse' },
    ],
    strengths: ['Industrie de pointe', 'Ingénierie', 'Commerce'],
    weaknesses: ['Peu de pétrole', 'Armée modeste', 'Dépendance énergétique'],
    bonuses: { researchBonus: 14, militaryBonus: 6, tradeBonus: 15, agricultureBonus: 5 },
  },
  {
    id: 'russia',
    name: 'Russie',
    flag: '🇷🇺',
    description: 'Immense territoire riche en énergie et en puissance militaire.',
    startingResources: { oil: 90, minerals: 80, agriculture: 35, water: 45 },
    startingMoney: 4800,
    startingPopulation: 14.5,
    regions: [
      { name: 'Moscou' }, { name: 'Sibérie' }, { name: 'Oural' },
      { name: 'Caucase' }, { name: 'Saint-Pétersbourg' }, { name: 'Extrême-Orient' },
    ],
    strengths: ['Pétrole massif', 'Armée puissante', 'Territoires vastes'],
    weaknesses: ['Bonheur bas', 'Agriculture fragile', 'Isolation diplomatique'],
    bonuses: { researchBonus: 8, militaryBonus: 18, tradeBonus: 4, agricultureBonus: 10 },
  },
  {
    id: 'india',
    name: 'Inde',
    flag: '🇮🇳',
    description: 'Sous-continent immense avec une population colossale et du potentiel tech.',
    startingResources: { oil: 25, minerals: 45, agriculture: 70, water: 40 },
    startingMoney: 4000,
    startingPopulation: 28.0,
    regions: [
      { name: 'Mumbai' }, { name: 'Delhi' }, { name: 'Bangalore' },
      { name: 'Kolkata' }, { name: 'Chennai' }, { name: 'Punjab' },
    ],
    strengths: ['Population massive', 'IT & services', 'Croissance rapide'],
    weaknesses: ['Eau limitée', 'Infrastructure faible', 'Pollution'],
    bonuses: { researchBonus: 12, militaryBonus: 8, tradeBonus: 10, agricultureBonus: 10 },
  },
  {
    id: 'usa',
    name: 'États-Unis',
    flag: '🇺🇸',
    description: 'Superpuissance équilibrée avec une forte capacité militaire et technologique.',
    startingResources: { oil: 65, minerals: 55, agriculture: 75, water: 70 },
    startingMoney: 6000,
    startingPopulation: 16.5,
    regions: [
      { name: 'Californie' }, { name: 'Texas' }, { name: 'New York' },
      { name: 'Midwest' }, { name: 'Floride' },
    ],
    strengths: ['Polyvalent', 'Militaire fort', 'Finance puissante'],
    weaknesses: ['Coûts élevés', 'Dépendance au pétrole', 'Pollution'],
    bonuses: { researchBonus: 12, militaryBonus: 14, tradeBonus: 10, agricultureBonus: 4 },
  },
  {
    id: 'nigeria',
    name: 'Nigeria',
    flag: '🇳🇬',
    description: 'Géant africain riche en pétrole avec une population en forte croissance.',
    startingResources: { oil: 75, minerals: 35, agriculture: 50, water: 35 },
    startingMoney: 3800,
    startingPopulation: 22.0,
    regions: [
      { name: 'Lagos' }, { name: 'Abuja' }, { name: 'Delta du Niger' },
      { name: 'Kano' }, { name: 'Imo' },
    ],
    strengths: ['Pétrole abondant', 'Population jeune', 'Croissance rapide'],
    weaknesses: ['Infrastructure faible', 'Recherche basse', 'Eau limitée'],
    bonuses: { researchBonus: 4, militaryBonus: 8, tradeBonus: 8, agricultureBonus: 20 },
  },
  {
    id: 'france',
    name: 'France',
    flag: '🇫🇷',
    description: 'Nation diplomate et culturelle, forte en tourisme et recherche nucléaire.',
    startingResources: { oil: 10, minerals: 30, agriculture: 65, water: 65 },
    startingMoney: 5200,
    startingPopulation: 6.7,
    regions: [
      { name: 'Île-de-France' }, { name: 'Provence' }, { name: 'Aquitaine' },
      { name: 'Bretagne' }, { name: 'Alsace' },
    ],
    strengths: ['Tourisme', 'Nucléaire', 'Diplomatie', 'Agriculture'],
    weaknesses: ['Peu de minerais', 'Industrie moyenne', 'Peu de pétrole'],
    bonuses: { researchBonus: 12, militaryBonus: 10, tradeBonus: 10, agricultureBonus: 8 },
  },
  {
    id: 'china',
    name: 'Chine',
    flag: '🇨🇳',
    description: 'Superpuissance industrielle et commerciale avec contrôle autoritaire.',
    startingResources: { oil: 40, minerals: 70, agriculture: 60, water: 45 },
    startingMoney: 5000,
    startingPopulation: 30.0,
    regions: [
      { name: 'Shanghai' }, { name: 'Pékin' }, { name: 'Guangdong' },
      { name: 'Sichuan' }, { name: 'Xinjiang' }, { name: 'Mandchourie' },
    ],
    strengths: ['Population immense', 'Industrie massive', 'Minerais'],
    weaknesses: ['Bonheur contrôlé', 'Eau limitée', 'Pollution élevée'],
    bonuses: { researchBonus: 10, militaryBonus: 12, tradeBonus: 12, agricultureBonus: 6 },
  },
  {
    id: 'saudi',
    name: 'Arabie Saoudite',
    flag: '🇸🇦',
    description: 'Royaume pétrolier richissime mais ultra-dépendant des hydrocarbures.',
    startingResources: { oil: 100, minerals: 20, agriculture: 10, water: 10 },
    startingMoney: 7000,
    startingPopulation: 3.5,
    regions: [
      { name: 'Riyad' }, { name: 'Djeddah' }, { name: 'Province Est' },
      { name: 'Médine' }, { name: 'Asir' },
    ],
    strengths: ['Pétrole illimité', 'Capital de départ élevé', 'Finance'],
    weaknesses: ['Eau critique', 'Agriculture nulle', 'Population faible'],
    bonuses: { researchBonus: 5, militaryBonus: 10, tradeBonus: 20, agricultureBonus: 5 },
  },
  {
    id: 'australia',
    name: 'Australie',
    flag: '🇦🇺',
    description: 'Île-continent riche en minerais avec un haut niveau de vie.',
    startingResources: { oil: 30, minerals: 85, agriculture: 55, water: 35 },
    startingMoney: 5500,
    startingPopulation: 2.6,
    regions: [
      { name: 'Sydney' }, { name: 'Melbourne' }, { name: 'Queensland' },
      { name: 'Australie-Occidentale' }, { name: 'Territoire du Nord' },
    ],
    strengths: ['Minerais riches', 'Bonheur élevé', 'Commerce stable'],
    weaknesses: ['Population très faible', 'Eau limitée', 'Isolé géographiquement'],
    bonuses: { researchBonus: 10, militaryBonus: 5, tradeBonus: 15, agricultureBonus: 10 },
  },
  {
    id: 'sweden',
    name: 'Suède',
    flag: '🇸🇪',
    description: 'Modèle scandinave : haut bonheur, écologie avancée, innovation.',
    startingResources: { oil: 5, minerals: 40, agriculture: 35, water: 75 },
    startingMoney: 5000,
    startingPopulation: 1.0,
    regions: [
      { name: 'Stockholm' }, { name: 'Göteborg' }, { name: 'Malmö' },
      { name: 'Norrland' }, { name: 'Dalécarlie' },
    ],
    strengths: ['Bonheur max', 'Écologie', 'Innovation', 'Eau abondante'],
    weaknesses: ['Population minuscule', 'Pas de pétrole', 'Armée faible'],
    bonuses: { researchBonus: 16, militaryBonus: 2, tradeBonus: 12, agricultureBonus: 10 },
  },

  // ─── Maghreb & Proche-Orient ───────────────────────────────
  {
    id: 'algeria',
    name: 'Algérie',
    flag: '🇩🇿',
    description: 'Plus grand pays d\'Afrique, puissance pétrolière et gazière avec une armée solide.',
    startingResources: { oil: 80, minerals: 50, agriculture: 35, water: 30 },
    startingMoney: 4600,
    startingPopulation: 4.4,
    regions: [
      { name: 'Alger' }, { name: 'Oran' }, { name: 'Constantine' },
      { name: 'Tamanrasset' }, { name: 'Annaba' },
    ],
    strengths: ['Pétrole & gaz', 'Armée solide', 'Territoire vaste', 'Minerais'],
    weaknesses: ['Eau limitée', 'Agriculture fragile', 'Économie peu diversifiée'],
    bonuses: { researchBonus: 6, militaryBonus: 16, tradeBonus: 8, agricultureBonus: 10 },
  },
  {
    id: 'morocco',
    name: 'Maroc',
    flag: '🇲🇦',
    description: 'Leader mondial du phosphate, nation commerçante ouverte entre Afrique et Europe.',
    startingResources: { oil: 5, minerals: 75, agriculture: 65, water: 40 },
    startingMoney: 4200,
    startingPopulation: 3.6,
    regions: [
      { name: 'Casablanca' }, { name: 'Rabat' }, { name: 'Marrakech' },
      { name: 'Fès' }, { name: 'Agadir' },
    ],
    strengths: ['Phosphates', 'Agriculture', 'Tourisme', 'Commerce ouvert'],
    weaknesses: ['Quasi pas de pétrole', 'Eau limitée', 'Industrie moyenne'],
    bonuses: { researchBonus: 8, militaryBonus: 6, tradeBonus: 14, agricultureBonus: 12 },
  },
  {
    id: 'tunisia',
    name: 'Tunisie',
    flag: '🇹🇳',
    description: 'Nation la plus ouverte du Maghreb : services, commerce et tourisme méditerranéen.',
    startingResources: { oil: 20, minerals: 35, agriculture: 55, water: 45 },
    startingMoney: 4000,
    startingPopulation: 1.1,
    regions: [
      { name: 'Tunis' }, { name: 'Sfax' }, { name: 'Sousse' },
      { name: 'Gabès' }, { name: 'Bizerte' },
    ],
    strengths: ['Commerce', 'Tourisme', 'Services', 'Formation'],
    weaknesses: ['Peu de ressources', 'Petite population', 'Industrie légère'],
    bonuses: { researchBonus: 12, militaryBonus: 4, tradeBonus: 16, agricultureBonus: 8 },
  },
  {
    id: 'libya',
    name: 'Libye',
    flag: '🇱🇾',
    description: 'Immenses réserves pétrolières, population réduite, désert saharo-méditerranéen.',
    startingResources: { oil: 95, minerals: 20, agriculture: 15, water: 10 },
    startingMoney: 5500,
    startingPopulation: 0.7,
    regions: [
      { name: 'Tripoli' }, { name: 'Benghazi' }, { name: 'Misrata' },
      { name: 'Sabha' }, { name: 'Tobrouk' },
    ],
    strengths: ['Pétrole immense', 'Capital de départ élevé', 'Fonds souverains'],
    weaknesses: ['Population ultra-réduite', 'Eau critique', 'Agriculture quasi nulle'],
    bonuses: { researchBonus: 4, militaryBonus: 8, tradeBonus: 18, agricultureBonus: 10 },
  },
  {
    id: 'israel',
    name: 'Israël',
    flag: '🇮🇱',
    description: 'Startup Nation : technologie de pointe, défense avancée et renseignement d\'élite.',
    startingResources: { oil: 10, minerals: 25, agriculture: 45, water: 35 },
    startingMoney: 5200,
    startingPopulation: 0.9,
    regions: [
      { name: 'Tel Aviv' }, { name: 'Jérusalem' }, { name: 'Haïfa' },
      { name: 'Néguev' }, { name: 'Galilée' },
    ],
    strengths: ['Recherche & Tech', 'Défense', 'Renseignement', 'Innovation'],
    weaknesses: ['Territoire restreint', 'Peu de ressources naturelles', 'Isolement régional'],
    bonuses: { researchBonus: 20, militaryBonus: 14, tradeBonus: 4, agricultureBonus: 2 },
  },
  {
    id: 'palestine',
    name: 'Palestine',
    flag: '🇵🇸',
    description: 'Nation résiliente à l\'économie agricole, bénéficiant d\'un fort soutien diplomatique international.',
    startingResources: { oil: 5, minerals: 15, agriculture: 55, water: 25 },
    startingMoney: 3200,
    startingPopulation: 0.5,
    regions: [
      { name: 'Gaza' }, { name: 'Ramallah' }, { name: 'Naplouse' },
      { name: 'Bethléem' }, { name: 'Jéricho' },
    ],
    strengths: ['Agriculture', 'Résilience', 'Soutien diplomatique', 'Coûts bas'],
    weaknesses: ['Capital de départ limité', 'Peu de ressources', 'Territoire contraint'],
    bonuses: { researchBonus: 6, militaryBonus: 4, tradeBonus: 18, agricultureBonus: 12 },
  },
];
